#!/bin/bash

#SBATCH	 -J	 sculptor_full
#SBATCH --ntasks=16				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 12:00:00
#SBATCH -p cosma			        #Queue name e.g. cosma, cosma6, etc.
#SBATCH -o %J.out		#Standard output file
#SBATCH --mem-per-cpu=4G


source ~/slurm_header.sh
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt 1 >> log.out


scontrol show job=$SLURM_JOB_ID
