#!/bin/bash
#SBATCH	 -J	ngc2566
#SBATCH --ntasks=16
#SBATCH -t 0:30:00
#SBATCH -o %J.out		
#SBATCH --mem-per-cpu=2gb
# #SBATCH --nodes=2
#SBATCH -p cosma			        
#SBATCH -A durham

source ~/slurm_header.sh
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt 2 2045 >> log.out
