#!/bin/bash

#SBATCH	 -J	ngc2566
#SBATCH --ntasks=16
#SBATCH -A durham
#SBATCH -t 3:00:00
#SBATCH -p cosma			        
#SBATCH -o %J.out		
#SBATCH --mem-per-cpu=4gb


mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt 2 1608 >> log.out
