ra = 49.131
ra_err = 0.0
ra_ref = "Richstein2024ApJ...967...72R"
dec = -50.009
dec_err = 0.0
dec_ref = "Richstein2024ApJ...967...72R"
distance = 77.98301105232593
distance_err = 7.523660236142476
distance_ref = "Kim2015ApJ...808L..39K"
pmra = 0.967
pmra_err = 0.173
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.771
pmdec_err = 0.23
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 103.0
PA_err = 14.0
PA_ref = "Richstein2024ApJ...967...72R"
ellipticity = 0.23
ellipticity_err = 0.08
ellipticity_ref = "Richstein2024ApJ...967...72R"
Mv = -2.0700000000000003
Mv_err = 0.1
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
