ra = 328.539
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cerny2023ApJ...942..111C"
dec = 26.62
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cerny2023ApJ...942..111C"
distance = 89.94975815300346
distance_em = 1.234156949207474
distance_ep = 1.2513257825875144
distance_modulus = 19.77
distance_modulus_em = 0.03
distance_modulus_ep = 0.03
distance_ref = "Cerny2023ApJ...942..111C"
pmra = 0.33
pmra_em = 0.07
pmra_ep = 0.07
pmra_ref = "Cerny2023ApJ...942..111C"
pmdec = -0.21
pmdec_em = 0.08
pmdec_ep = 0.08
pmdec_ref = "Cerny2023ApJ...942..111C"
radial_velocity = -273.6
radial_velocity_em = 1.5
radial_velocity_ep = 1.6
radial_velocity_ref = "Cerny2023ApJ...942..111C"
sigma_v = 3.3
sigma_v_em = 1.1
sigma_v_ep = 1.7
sigma_v_ref = "Cerny2023ApJ...942..111C"
position_angle = 0 # 115.0
position_angle_em = nan #41.0
position_angle_ep = nan #27.0
postiion_angle_ref = "Cerny2023ApJ...942..111C"
ellipticity = 0
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Cerny2023ApJ...942..111C"
Mv = -4.25
Mv_em = 0.2
Mv_ep = 0.2
mv = 15.52
mv_em = 0.2
mv_ep = 0.2
mv_ref = "Cerny2023ApJ...942..111C"
r_h = 1.6
r_h_em = 0.25
r_h_ep = 0.29
r_h_ref = "Cerny2023ApJ...942..111C"
metallicity = -2.67
metallicity_em = 0.29
metallicity_ep = 0.25
metallicity_ref = "Cerny2023ApJ...942..111C"
pmra_gsr = 0.22522555464833247
pmdec_gsr = 4.333897999635678e-5
radial_velocity_gsr = -48.8140231138431
theta_pm_gsr = -39.64
