#!/bin/bash

#SBATCH	 -J	 isolation
#SBATCH --ntasks=8				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 8:00:00
#SBATCH --mem-per-cpu=4G		#Memory per core
#SBATCH -p cosma			        #Queue name e.g. cosma, cosma6, etc.
#SBATCH --mail-user=dboyea@uvic.ca
#SBATCH --mail-type=END				#Notifications for job done & fail
#SBATCH -o %J.out		#Standard output file

module load gnu_comp
module load openmpi
module load fftw
module load hdf5
module load gsl

mpirun -np $SLURM_NTASKS $GADGET_DIR/Gadget param.txt 1 >> log.out

scontrol show job=$SLURM_JOB_ID
