ra = 164.261
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cerny2023ApJ...953....1C"
dec = 28.875
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cerny2023ApJ...953....1C"
distance = 81.65823713585922
distance_em = 6.841287084743854
distance_ep = 4.2431150146802
distance_modulus = 19.56
distance_modulus_em = 0.19
distance_modulus_ep = 0.11
distance_ref = "Cerny2023ApJ...953....1C"
pmra = -0.01
pmra_em = 0.4
pmra_ep = 0.39
pmra_ref = "Cerny2023ApJ...953....1C"
pmdec = -1.29
pmdec_em = 0.4
pmdec_ep = 0.37
pmdec_ref = "Cerny2023ApJ...953....1C"
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 0
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "Cerny2023ApJ...953....1C"
ellipticity = 0
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Cerny2023ApJ...953....1C"
Mv = -2.3999999999999986
Mv_em = 0.4
Mv_ep = 0.5
mv = 17.16
mv_em = 0.4
mv_ep = 0.5
mv_ref = "Cerny2023ApJ...953....1C"
r_h = 1.09
r_h_em = 0.35
r_h_ep = 0.37
r_h_ref = "Cerny2023ApJ...953....1C"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
