ra = 37.389
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Koposov2018MNRAS.479.5343K"
dec = -79.3089
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Koposov2018MNRAS.479.5343K"
distance = 27.542287033381633
distance_em = 0.5027033922931707
distance_ep = 0.5120493461354698
distance_modulus = 17.2
distance_modulus_em = 0.04
distance_modulus_ep = 0.04
distance_ref = "Koposov2018MNRAS.479.5343K"
pmra = 3.781
pmra_em = 0.016
pmra_ep = 0.016
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.496
pmdec_em = 0.015
pmdec_ep = 0.015
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 80.4
radial_velocity_em = 0.6
radial_velocity_ep = 0.6
radial_velocity_ref = "Koposov2018MNRAS.479.5343K"
sigma_v = 2.7
sigma_v_em = 0.43
sigma_v_ep = 0.51
sigma_v_ref = "Koposov2018MNRAS.479.5343K"
position_angle = 97.0
position_angle_em = 14.0
position_angle_ep = 14.0
postiion_angle_ref = "Koposov2018MNRAS.479.5343K"
ellipticity = 0.21
ellipticity_em = 0.07
ellipticity_ep = 0.15
ellipticity_ref = "Koposov2018MNRAS.479.5343K"
Mv = -4.709999999999999
Mv_em = 0.08
Mv_ep = 0.08
mv = 12.49
mv_em = 0.08
mv_ep = 0.08
mv_ref = "Koposov2018MNRAS.479.5343K"
rh = 7.42
rh_em = 0.54
rh_ep = 0.62
rh_ref = "Koposov2018MNRAS.479.5343K"
metallicity = -2.52
metallicity_em = 0.09
metallicity_ep = 0.09
metallicity_ref = "Koposov2018MNRAS.479.5343K"
