ra = 164.261
ra_err = 0.0
ra_ref = "Cerny2023ApJ...953....1C"
dec = 28.875
dec_err = 0.0
dec_ref = "Cerny2023ApJ...953....1C"
distance = 81.65823713585922
distance_err = 6.841287084743854
distance_ref = "Cerny2023ApJ...953....1C"
pmra = -0.01
pmra_err = 0.4
pmra_ref = "Cerny2023ApJ...953....1C"
pmdec = -1.29
pmdec_err = 0.4
pmdec_ref = "Cerny2023ApJ...953....1C"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = nan
PA_err = nan
PA_ref = "Cerny2023ApJ...953....1C"
ellipticity = nan
ellipticity_err = nan
ellipticity_ref = "Cerny2023ApJ...953....1C"
Mv = -2.3999999999999986
Mv_err = 0.5
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
