ra = 284.095116792971
ra_em = 0.0
ra_ep = 0.0
ra_ref = "McConnachie2012AJ....144....4M"
dec = -30.549906
dec_em = 0.0
dec_ep = 0.0
dec_ref = "McConnachie2012AJ....144....4M"
distance = 26.302679918953814
distance_em = 1.755590762103477
distance_ep = 1.8811493936907375
distance_modulus = 17.1
distance_modulus_em = 0.15
distance_modulus_ep = 0.15
distance_ref = "McConnachie2012AJ....144....4M"
pmra = -2.679
pmra_em = 0.001
pmra_ep = 0.001
pmra_ref = "An2024MNRAS.532.3713A"
pmdec = -1.394
pmdec_em = 0.001
pmdec_ep = 0.001
pmdec_ref = "An2024MNRAS.532.3713A"
radial_velocity = 140.0
radial_velocity_em = 2.0
radial_velocity_ep = 2.0
radial_velocity_ref = "McConnachie2012AJ....144....4M"
sigma_v = 11.4
sigma_v_em = 0.7
sigma_v_ep = 0.7
sigma_v_ref = "McConnachie2012AJ....144....4M"
position_angle = 102.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "McConnachie2012AJ....144....4M"
ellipticity = 0.64
ellipticity_em = 0.02
ellipticity_ep = 0.02
ellipticity_ref = "McConnachie2012AJ....144....4M"
Mv = -13.500000000000002
Mv_em = 0.3
Mv_ep = 0.3
mv = 3.6
mv_em = 0.3
mv_ep = 0.3
mv_ref = "McConnachie2012AJ....144....4M"
rh = 342.0
rh_em = 12.0
rh_ep = 12.0
rh_ref = "McConnachie2012AJ....144....4M"
metallicity = -0.53
metallicity_em = 0.02
metallicity_ep = 0.03
metallicity_ref = "Simon2019ARA&A..57..375S"
