ra = 233.689
ra_err = 0.0
ra_ref = "Homma2019PASJ...71...94H"
dec = 43.726
dec_err = 0.0
dec_ref = "Homma2019PASJ...71...94H"
distance = 208.9296130854041
distance_err = 20.15715219137337
distance_ref = "Homma2019PASJ...71...94H"
pmra = 0.469
pmra_err = 0.244
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.489
pmdec_err = 0.256
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 3.0
PA_err = 4.0
PA_ref = "Homma2019PASJ...71...94H"
ellipticity = 0.64
ellipticity_err = 0.05
ellipticity_ref = "Homma2019PASJ...71...94H"
Mv = -5.34
Mv_err = 0.29
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
