ra = 143.7225
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Higgs2021MNRAS.503..176H"
dec = 17.05138889
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Higgs2021MNRAS.503..176H"
distance = 413.04750199016104
distance_em = 14.94033143666411
distance_ep = 15.501018407278139
distance_modulus = 23.08
distance_modulus_em = 0.08
distance_modulus_ep = 0.08
distance_ref = "Higgs2021MNRAS.503..176H"
pmra = -0.007
pmra_em = 0.242
pmra_ep = 0.242
pmra_ref = "Bennet2024ApJ...971...98B"
pmdec = 0.11
pmdec_em = 0.168
pmdec_ep = 0.168
pmdec_ref = "Bennet2024ApJ...971...98B"
radial_velocity = 38.1
radial_velocity_em = 2.0
radial_velocity_ep = 2.0
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 7.5
sigma_v_em = 1.6
sigma_v_ep = 1.6
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = 121.13
position_angle_em = 34.66
position_angle_ep = 34.66
postiion_angle_ref = "Higgs2021MNRAS.503..176H"
ellipticity = 0.12
ellipticity_em = 0.08
ellipticity_ep = 0.08
ellipticity_ref = "Higgs2021MNRAS.503..176H"
Mv = -7.979999999999999
Mv_em = 0.5
Mv_ep = 0.5
mv = 15.1
mv_em = 0.5
mv_ep = 0.5
mv_ref = "McConnachie2012AJ....144....4M"
rh = 1.39
rh_em = 0.2
rh_ep = 0.2
rh_ref = "Higgs2021MNRAS.503..176H"
metallicity = -1.74
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Kirby2013ApJ...779..102K"
