ra = 33.3155
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Carlin2017AJ....154..267C"
dec = 36.1691
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Carlin2017AJ....154..267C"
distance = 28.44461107447914
distance_em = 1.4050274333906785
distance_ep = 1.478035291602751
distance_modulus = 17.27
distance_modulus_em = 0.11
distance_modulus_ep = 0.11
distance_ref = "Carlin2017AJ....154..267C"
pmra = 0.575
pmra_em = 0.06
pmra_ep = 0.06
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.112
pmdec_em = 0.067
pmdec_ep = 0.069
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -381.7
radial_velocity_em = 1.1
radial_velocity_ep = 1.1
radial_velocity_ref = "Kirby2017ApJ...838...83K"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Kirby2017ApJ...838...83K"
position_angle = 73.0
position_angle_em = 17.0
position_angle_ep = 17.0
postiion_angle_ref = "Carlin2017AJ....154..267C"
ellipticity = 0.3
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Carlin2017AJ....154..267C"
Mv = -1.299999999999999
Mv_em = 0.25
Mv_ep = 0.23
mv = 15.97
mv_em = 0.25
mv_ep = 0.23
mv_ref = "Richstein2024ApJ...967...72R"
rh = 2.5
rh_em = 0.3
rh_ep = 0.3
rh_ref = "Carlin2017AJ....154..267C"
metallicity = -2.24
metallicity_em = 0.05
metallicity_ep = 0.05
metallicity_ref = "Kirby2017ApJ...838...83K"
