ra = 354.9919
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2024ApJ...967...72R"
dec = -54.4019
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2024ApJ...967...72R"
distance = 83.17637711026708
distance_em = 7.318619607348566
distance_ep = 8.02470682532389
distance_modulus = 19.6
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "MutluPakdil2018ApJ...863...25M"
pmra = 0.507
pmra_em = 0.048
pmra_ep = 0.047
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.199
pmdec_em = 0.057
pmdec_ep = 0.058
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 32.4
radial_velocity_em = 3.75
radial_velocity_ep = 3.75
radial_velocity_ref = "Fritz2019A&A...623A.129F"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Fritz2019A&A...623A.129F"
position_angle = -33.0
position_angle_em = 5.0
position_angle_ep = 5.0
postiion_angle_ref = "Richstein2024ApJ...967...72R"
ellipticity = 0.44
ellipticity_em = 0.06
ellipticity_ep = 0.06
ellipticity_ref = "Richstein2024ApJ...967...72R"
Mv = -2.6000000000000014
Mv_em = 0.09
Mv_ep = 0.13
mv = 17.0
mv_em = 0.09
mv_ep = 0.13
mv_ref = "Richstein2024ApJ...967...72R"
rh = 1.5
rh_em = 0.17
rh_ep = 0.2
rh_ref = "Richstein2024ApJ...967...72R"
metallicity = -2.51
metallicity_em = 0.17
metallicity_ep = 0.19
metallicity_ref = "Fritz2019A&A...623A.129F"
