ra = 172.7857
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 2.2194
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 169.04409316432634
distance_em = 4.606920842833091
distance_ep = 4.735989710611278
distance_modulus = 21.14
distance_modulus_em = 0.06
distance_modulus_ep = 0.06
distance_ref = "Medina2018ApJ...855...43M"
pmra = 0.1186
pmra_em = 0.1943
pmra_ep = 0.1943
pmra_ref = "Julio2024A&A...687A.212J"
pmdec = -0.1183
pmdec_em = 0.1704
pmdec_ep = 0.1704
pmdec_ref = "Julio2024A&A...687A.212J"
radial_velocity = 173.1
radial_velocity_em = 0.8
radial_velocity_ep = 1.0
radial_velocity_ref = "Jenkins2021ApJ...920...92J"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Jenkins2021ApJ...920...92J"
position_angle = -71.0
position_angle_em = 26.0
position_angle_ep = 26.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.43
ellipticity_em = 0.22
ellipticity_ep = 0.22
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -4.400000000000002
Mv_em = 0.36
Mv_ep = 0.36
mv = 16.74
mv_em = 0.36
mv_ep = 0.36
mv_ref = "Munoz2018ApJ...860...66M"
rh = 1.0
rh_em = 0.32
rh_ep = 0.32
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.29
metallicity_em = 0.17
metallicity_ep = 0.14
metallicity_ref = "Jenkins2021ApJ...920...92J"
