ra = 209.5141
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 12.8553
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 41.68693834703355
distance_em = 1.1360848021951213
distance_ep = 1.1679136927103642
distance_modulus = 18.1
distance_modulus_em = 0.06
distance_modulus_ep = 0.06
distance_ref = "Walsh2008ApJ...688..245W"
pmra = -2.426
pmra_em = 0.077
pmra_ep = 0.08
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.414
pmdec_em = 0.061
pmdec_ep = 0.061
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -130.4
radial_velocity_em = 1.1
radial_velocity_ep = 1.4
radial_velocity_ref = "Bruce2023ApJ...950..167B"
sigma_v = 2.9
sigma_v_em = 1.2
sigma_v_ep = 1.6
sigma_v_ref = "Bruce2023ApJ...950..167B"
position_angle = -68.0
position_angle_em = 27.0
position_angle_ep = 27.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.25
ellipticity_em = 0.11
ellipticity_ep = 0.11
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -2.9400000000000013
Mv_em = 0.25
Mv_ep = 0.25
mv = 15.16
mv_em = 0.25
mv_ep = 0.25
mv_ref = "Munoz2018ApJ...860...66M"
rh = 3.17
rh_em = 0.42
rh_ep = 0.42
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.71
metallicity_em = 0.1
metallicity_ep = 0.11
metallicity_ref = "Bruce2023ApJ...950..167B"
