ra = 49.131
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2024ApJ...967...72R"
dec = -50.009
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2024ApJ...967...72R"
distance = 77.98301105232593
distance_em = 6.861659686992979
distance_ep = 7.523660236142476
distance_modulus = 19.46
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Kim2015ApJ...808L..39K"
pmra = 0.967
pmra_em = 0.171
pmra_ep = 0.173
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.771
pmdec_em = 0.23
pmdec_ep = 0.22
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 103.0
position_angle_em = 14.0
position_angle_ep = 11.0
postiion_angle_ref = "Richstein2024ApJ...967...72R"
ellipticity = 0.23
ellipticity_em = 0.08
ellipticity_ep = 0.07
ellipticity_ref = "Richstein2024ApJ...967...72R"
Mv = -2.0700000000000003
Mv_em = 0.1
Mv_ep = 0.1
mv = 17.39
mv_em = 0.1
mv_ep = 0.1
mv_ref = "Richstein2024ApJ...967...72R"
rh = 1.69
rh_em = 0.17
rh_ep = 0.18
rh_ref = "Richstein2024ApJ...967...72R"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
