ra = 100.4065
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = -50.9593
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 105.58445924300804
distance_em = 5.261577185208139
distance_ep = 5.537528133865379
distance_modulus = 20.118
distance_modulus_em = 0.111
distance_modulus_ep = 0.111
distance_ref = "Karczmarek2015AJ....150...90K"
pmra = 0.532
pmra_em = 0.006
pmra_ep = 0.007
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.127
pmdec_em = 0.006
pmdec_ep = 0.006
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 222.9
radial_velocity_em = 0.1
radial_velocity_ep = 0.1
radial_velocity_ref = "Walker2009AJ....137.3100W"
sigma_v = 6.6
sigma_v_em = 1.2
sigma_v_ep = 1.2
sigma_v_ref = "Walker2009AJ....137.3100W"
position_angle = 60.0
position_angle_em = 1.0
position_angle_ep = 1.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.36
ellipticity_em = 0.01
ellipticity_ep = 0.01
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -9.429999999999998
Mv_em = 0.05
Mv_ep = 0.05
mv = 10.688
mv_em = 0.05
mv_ep = 0.05
mv_ref = "Munoz2018ApJ...860...66M"
rh = 10.1
rh_em = 0.1
rh_ep = 0.1
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.8
metallicity_em = 0.02
metallicity_ep = 0.02
metallicity_ref = "Simon2019ARA&A..57..375S"
