ra = 43.8755
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2024ApJ...967...72R"
dec = -54.1174
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2024ApJ...967...72R"
distance = 79.43282347242821
distance_em = 3.5750659695098506
distance_ep = 3.743553637838872
distance_modulus = 19.5
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "Koposov2015ApJ...805..130K"
pmra = 0.847
pmra_em = 0.035
pmra_ep = 0.034
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.607
pmdec_em = 0.035
pmdec_ep = 0.035
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 112.8
radial_velocity_em = 2.6
radial_velocity_ep = 2.5
radial_velocity_ref = "Koposov2015ApJ...811...62K"
sigma_v = 4.9
sigma_v_em = 0.9
sigma_v_ep = 2.8
sigma_v_ref = "Koposov2015ApJ...811...62K"
position_angle = 44.0
position_angle_em = 6.0
position_angle_ep = 6.0
postiion_angle_ref = "Richstein2024ApJ...967...72R"
ellipticity = 0.27
ellipticity_em = 0.05
ellipticity_ep = 0.05
ellipticity_ref = "Richstein2024ApJ...967...72R"
Mv = -3.379999999999999
Mv_em = 0.09
Mv_ep = 0.06
mv = 16.12
mv_em = 0.09
mv_ep = 0.06
mv_ref = "Richstein2024ApJ...967...72R"
rh = 1.61
rh_em = 0.13
rh_ep = 0.13
rh_ref = "Richstein2024ApJ...967...72R"
metallicity = -2.76
metallicity_em = 0.1
metallicity_ep = 0.1
metallicity_ref = "Koposov2015ApJ...811...62K"
