ra = 210.02
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 14.5135
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 66.37430704019089
distance_em = 2.4008234919260687
distance_ep = 2.4909225942365936
distance_modulus = 19.11
distance_modulus_em = 0.08
distance_modulus_ep = 0.08
distance_ref = "DallOra2006ApJ...653L.109D"
pmra = -0.385
pmra_em = 0.017
pmra_ep = 0.017
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.068
pmdec_em = 0.013
pmdec_ep = 0.013
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 101.8
radial_velocity_em = 0.7
radial_velocity_ep = 0.7
radial_velocity_ref = "Koposov2011ApJ...736..146K"
sigma_v = 4.6
sigma_v_em = 0.6
sigma_v_ep = 0.8
sigma_v_ref = "Koposov2011ApJ...736..146K"
position_angle = 6.0
position_angle_em = 3.0
position_angle_ep = 3.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.3
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -6.02
Mv_em = 0.25
Mv_ep = 0.25
mv = 13.09
mv_em = 0.25
mv_ep = 0.25
mv_ref = "Munoz2018ApJ...860...66M"
rh = 9.97
rh_em = 0.27
rh_ep = 0.27
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.35
metallicity_em = 0.08
metallicity_ep = 0.09
metallicity_ref = "Simon2019ARA&A..57..375S"
