ra = 15.0183
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = -33.7186
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 83.94599865193982
distance_em = 1.5321871506395155
distance_ep = 1.5606726365285937
distance_modulus = 19.62
distance_modulus_em = 0.04
distance_modulus_ep = 0.04
distance_ref = "MartinezVazquez2015MNRAS.454.1509M"
pmra = 0.1
pmra_em = 0.002
pmra_ep = 0.002
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.158
pmdec_em = 0.002
pmdec_ep = 0.002
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 111.4
radial_velocity_em = 0.1
radial_velocity_ep = 0.1
radial_velocity_ref = "Walker2009AJ....137.3100W"
sigma_v = 9.2
sigma_v_em = 1.1
sigma_v_ep = 1.1
sigma_v_ref = "Walker2009AJ....137.3100W"
position_angle = 92.0
position_angle_em = 1.0
position_angle_ep = 1.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.33
ellipticity_em = 0.01
ellipticity_ep = 0.01
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -10.770000000000001
Mv_em = 0.14
Mv_ep = 0.14
mv = 8.85
mv_em = 0.14
mv_ep = 0.14
mv_ref = "Munoz2018ApJ...860...66M"
rh = 11.17
rh_em = 0.05
rh_ep = 0.05
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.73
metallicity_em = 0.02
metallicity_ep = 0.03
metallicity_ref = "Simon2019ARA&A..57..375S"
