ra = 233.689
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Homma2019PASJ...71...94H"
dec = 43.726
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Homma2019PASJ...71...94H"
distance = 208.9296130854041
distance_em = 18.38354128907926
distance_ep = 20.15715219137337
distance_modulus = 21.6
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Homma2019PASJ...71...94H"
pmra = 0.469
pmra_em = 0.244
pmra_ep = 0.18
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.489
pmdec_em = 0.255
pmdec_ep = 0.256
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 3.0
position_angle_em = 4.0
position_angle_ep = 4.0
postiion_angle_ref = "Homma2019PASJ...71...94H"
ellipticity = 0.64
ellipticity_em = 0.05
ellipticity_ep = 0.05
ellipticity_ref = "Homma2019PASJ...71...94H"
Mv = -5.34
Mv_em = 0.17
Mv_ep = 0.29
mv = 16.26
mv_em = 0.17
mv_ep = 0.29
mv_ref = "Homma2024PASJ...76..733H"
rh = 7.6
rh_em = 0.8
rh_ep = 0.8
rh_ref = "Homma2019PASJ...71...94H"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
