ra = 225.449
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 66.9682
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 45.08167045414601
distance_em = 5.087195478036307
distance_ep = 5.037052908581245
distance_modulus = 18.27
distance_modulus_em = 0.26
distance_modulus_ep = 0.23
distance_ref = "Munoz2012ApJ...753L..15M"
pmra = -0.1
pmra_em = 0.203
pmra_ep = 0.203
pmra_ref = "Vasiliev2021MNRAS.505.5978V"
pmdec = -0.02
pmdec_em = 0.207
pmdec_ep = 0.207
pmdec_ref = "Vasiliev2021MNRAS.505.5978V"
radial_velocity = -137.0
radial_velocity_em = 4.0
radial_velocity_ep = 4.0
radial_velocity_ref = "Munoz2012ApJ...753L..15M"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Munoz2012ApJ...753L..15M"
position_angle = 139.0
position_angle_em = 46.0
position_angle_ep = 46.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.34
ellipticity_em = 0.17
ellipticity_ep = 0.17
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -0.3999999999999986
Mv_em = 0.97
Mv_ep = 0.97
mv = 17.87
mv_em = 0.97
mv_ep = 0.97
mv_ref = "Munoz2018ApJ...860...66M"
rh = 0.49
rh_em = 0.15
rh_ep = 0.15
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.46
metallicity_em = 0.32
metallicity_ep = 0.32
metallicity_ref = "Munoz2012ApJ...753L..15M"
