ra = 357.218
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cerny2024arXiv241000981C"
dec = -3.489
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cerny2024arXiv241000981C"
distance = 85.50667128846841
distance_em = 4.223619672058462
distance_ep = 4.443086864535061
distance_modulus = 19.66
distance_modulus_em = 0.11
distance_modulus_ep = 0.11
distance_ref = "Cerny2024arXiv241000981C"
pmra = 1.01
pmra_em = 0.25
pmra_ep = 0.26
pmra_ref = "Cerny2024arXiv241000981C"
pmdec = -0.11
pmdec_em = 0.19
pmdec_ep = 0.19
pmdec_ref = "Cerny2024arXiv241000981C"
radial_velocity = -13.1
radial_velocity_em = 1.0
radial_velocity_ep = 1.0
radial_velocity_ref = "Cerny2024arXiv241000981C"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Cerny2024arXiv241000981C"
position_angle = 120.0
position_angle_em = 15.0
position_angle_ep = 12.0
postiion_angle_ref = "Cerny2024arXiv241000981C"
ellipticity = 0.47
ellipticity_em = 0.14
ellipticity_ep = 0.28
ellipticity_ref = "Cerny2024arXiv241000981C"
Mv = -2.5
Mv_em = 0.4
Mv_ep = 0.5
mv = 17.16
mv_em = 0.4
mv_ep = 0.5
mv_ref = "Cerny2024arXiv241000981C"
rh = 2.1
rh_em = 0.5
rh_ep = 0.7
rh_ref = "Cerny2024arXiv241000981C"
metallicity = -2.61
metallicity_em = 0.2
metallicity_ep = 0.2
metallicity_ref = "Cerny2024arXiv241000981C"
