ra = 180.038
ra_err = 0.0
ra_ref = "Homma2018PASJ...70S..18H"
dec = -0.681
dec_err = 0.0
dec_ref = "Homma2018PASJ...70S..18H"
distance = 91.20108393559097
distance_err = 8.798916064409028
distance_ref = "Homma2024PASJ...76..733H"
pmra = nan
pmra_err = nan
pmra_ref = nan
pmdec = nan
pmdec_err = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 62.0
PA_err = 13.0
PA_ref = "Homma2018PASJ...70S..18H"
ellipticity = 0.59
ellipticity_err = 0.14
ellipticity_ref = "Homma2018PASJ...70S..18H"
Mv = -0.9000000000000021
Mv_err = 0.72
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
