ra = 247.7722
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 12.7852
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 130.61708881318404
distance_em = 5.878737388889974
distance_ep = 6.155793746400917
distance_modulus = 20.58
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "MutluPakdil2020ApJ...902..106M"
pmra = -0.035
pmra_em = 0.042
pmra_ep = 0.042
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.339
pmdec_em = 0.036
pmdec_ep = 0.035
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 45.0
radial_velocity_em = 1.1
radial_velocity_ep = 1.1
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 5.1
sigma_v_em = 0.9
sigma_v_ep = 0.9
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = -73.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.69
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -5.806999999999999
Mv_em = 0.17
Mv_ep = 0.17
mv = 14.773
mv_em = 0.17
mv_ep = 0.17
mv_ref = "Munoz2018ApJ...860...66M"
rh = 5.63
rh_em = 0.46
rh_ep = 0.46
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.47
metallicity_em = 0.12
metallicity_ep = 0.13
metallicity_ref = "Simon2019ARA&A..57..375S"
