ra = 27.775
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Battaglia2012MNRAS.424.1113B"
dec = -44.445
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Battaglia2012MNRAS.424.1113B"
distance = 409.26065973001096
distance_em = 22.003014808394482
distance_ep = 41.556044811449055
distance_modulus = 23.06
distance_modulus_em = 0.12
distance_modulus_ep = 0.21
distance_ref = "Battaglia2012MNRAS.424.1113B"
pmra = 0.142
pmra_em = 0.028
pmra_ep = 0.028
pmra_ref = "Bennet2024ApJ...971...98B"
pmdec = -0.04
pmdec_em = 0.032
pmdec_ep = 0.032
pmdec_ref = "Bennet2024ApJ...971...98B"
radial_velocity = -21.2
radial_velocity_em = 1.0
radial_velocity_ep = 1.0
radial_velocity_ref = "Kacharov2017MNRAS.466.2006K"
sigma_v = 9.3
sigma_v_em = 0.7
sigma_v_ep = 0.7
sigma_v_ref = "Kacharov2017MNRAS.466.2006K"
position_angle = 8.0
position_angle_em = 4.0
position_angle_ep = 4.0
postiion_angle_ref = "Battaglia2012MNRAS.424.1113B"
ellipticity = 0.3
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Battaglia2012MNRAS.424.1113B"
Mv = -9.87
Mv_em = 0.4
Mv_ep = 0.4
mv = 13.19
mv_em = 0.4
mv_ep = 0.4
mv_ref = "vandeRydt1991AJ....102..130V"
rh = 2.43
rh_em = 0.02
rh_ep = 0.02
rh_ref = "Battaglia2012MNRAS.424.1113B"
metallicity = -1.49
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Kacharov2017MNRAS.466.2006K"
