ra = 225.059
ra_err = 0.0
ra_ref = "Cerny2023ApJ...953....1C"
dec = 5.909
dec_err = 0.0
dec_ref = "Cerny2023ApJ...953....1C"
distance = 72.44359600749905
distance_err = 7.72421033126885
distance_ref = "Cerny2023ApJ...953....1C"
pmra = nan
pmra_err = nan
pmra_ref = nan
pmdec = nan
pmdec_err = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = nan
PA_err = nan
PA_ref = "Cerny2023ApJ...953....1C"
ellipticity = nan
ellipticity_err = nan
ellipticity_ref = "Cerny2023ApJ...953....1C"
Mv = -1.6000000000000014
Mv_err = 0.6
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
