ra = 132.8726
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 63.1335
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 34.673685045253166
distance_em = 2.0149018280195676
distance_ep = 2.1392123189999595
distance_modulus = 17.7
distance_modulus_em = 0.13
distance_modulus_ep = 0.13
distance_ref = "DallOra2012ApJ...752...42D"
pmra = 1.731
pmra_em = 0.021
pmra_ep = 0.021
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.906
pmdec_em = 0.025
pmdec_ep = 0.024
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -116.5
radial_velocity_em = 1.9
radial_velocity_ep = 1.9
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 6.7
sigma_v_em = 1.4
sigma_v_ep = 1.4
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = -76.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.56
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -4.42
Mv_em = 0.26
Mv_ep = 0.26
mv = 13.28
mv_em = 0.26
mv_ep = 0.26
mv_ref = "Munoz2018ApJ...860...66M"
rh = 13.8
rh_em = 0.5
rh_ep = 0.5
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.23
metallicity_em = 0.24
metallicity_ep = 0.21
metallicity_ref = "Simon2019ARA&A..57..375S"
