ra = 354.347
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Simon2020ApJ...892..137S"
dec = -63.266
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Simon2020ApJ...892..137S"
distance = 54.954087385762485
distance_em = 5.065638639761318
distance_ep = 5.580000089628875
distance_modulus = 18.7
distance_modulus_em = 0.21
distance_modulus_ep = 0.21
distance_ref = "Simon2020ApJ...892..137S"
pmra = -0.14
pmra_em = 0.05
pmra_ep = 0.04
pmra_ref = "Battaglia2022A&A...657A..54B"
pmdec = -1.18
pmdec_em = 0.06
pmdec_ep = 0.05
pmdec_ref = "Battaglia2022A&A...657A..54B"
radial_velocity = -34.7
radial_velocity_em = 0.8
radial_velocity_ep = 0.9
radial_velocity_ref = "Hansen2024ApJ...968...21H"
sigma_v = 1.2
sigma_v_em = 0.6
sigma_v_ep = 0.9
sigma_v_ref = "Hansen2024ApJ...968...21H"
position_angle = 29.0
position_angle_em = 11.0
position_angle_ep = 11.0
postiion_angle_ref = "Simon2020ApJ...892..137S"
ellipticity = 0.51
ellipticity_em = 0.18
ellipticity_ep = 0.09
ellipticity_ref = "Simon2020ApJ...892..137S"
Mv = -1.0999999999999979
Mv_em = 0.6
Mv_ep = 0.5
mv = 17.6
mv_em = 0.6
mv_ep = 0.5
mv_ref = "Simon2020ApJ...892..137S"
rh = 2.1
rh_em = 0.4
rh_ep = 0.6
rh_ref = "Simon2020ApJ...892..137S"
metallicity = -2.84
metallicity_em = 0.3
metallicity_ep = 0.32
metallicity_ref = "Hansen2024ApJ...968...21H"
