ra = 173.2405
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = -0.5453
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 151.35612484362073
distance_em = 4.1248746003487895
distance_ep = 4.24043831688644
distance_modulus = 20.9
distance_modulus_em = 0.06
distance_modulus_ep = 0.06
distance_ref = "Medina2018ApJ...855...43M"
pmra = -0.1921
pmra_em = 0.0514
pmra_ep = 0.0514
pmra_ref = "Julio2024A&A...687A.212J"
pmdec = -0.0686
pmdec_em = 0.0523
pmdec_ep = 0.0523
pmdec_ref = "Julio2024A&A...687A.212J"
radial_velocity = 131.6
radial_velocity_em = 1.2
radial_velocity_ep = 1.0
radial_velocity_ref = "Jenkins2021ApJ...920...92J"
sigma_v = 3.4
sigma_v_em = 0.9
sigma_v_ep = 1.3
sigma_v_ref = "Jenkins2021ApJ...920...92J"
position_angle = -28.0
position_angle_em = 38.0
position_angle_ep = 38.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.17
ellipticity_em = 0.09
ellipticity_ep = 0.09
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -4.949999999999999
Mv_em = 0.26
Mv_ep = 0.26
mv = 15.95
mv_em = 0.26
mv_ep = 0.26
mv_ref = "Munoz2018ApJ...860...66M"
rh = 2.54
rh_em = 0.27
rh_ep = 0.27
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.48
metallicity_em = 0.13
metallicity_ep = 0.16
metallicity_ref = "Jenkins2021ApJ...920...92J"
