ra = 31.331
ra_err = 0.0
ra_ref = "Homma2018PASJ...70S..18H"
dec = -4.27
dec_err = 0.0
dec_ref = "Homma2018PASJ...70S..18H"
distance = 251.1886431509582
distance_err = 24.23422718285812
distance_ref = "Homma2024PASJ...76..733H"
pmra = nan
pmra_err = nan
pmra_ref = nan
pmdec = nan
pmdec_err = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 101.0
PA_err = 6.0
PA_ref = "Homma2018PASJ...70S..18H"
ellipticity = 0.76
ellipticity_err = 0.08
ellipticity_ref = "Homma2018PASJ...70S..18H"
Mv = -3.4499999999999993
Mv_err = 0.49
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
