ra = 39.9583
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Wang2019ApJ...881..118W"
dec = -34.4997
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Wang2019ApJ...881..118W"
distance = 142.5607593602188
distance_em = 3.1167054730727273
distance_ep = 3.186366765434002
distance_modulus = 20.77
distance_modulus_em = 0.048
distance_modulus_ep = 0.048
distance_ref = "Oakes2022ApJ...929..116O"
pmra = 0.381
pmra_em = 0.001
pmra_ep = 0.001
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.359
pmdec_em = 0.002
pmdec_ep = 0.002
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 55.2
radial_velocity_em = 0.1
radial_velocity_ep = 0.1
radial_velocity_ref = "Walker2009AJ....137.3100W"
sigma_v = 12.1
sigma_v_em = 0.2
sigma_v_ep = 0.2
sigma_v_ref = "Walker2009AJ....137.3100W"
position_angle = 42.7
position_angle_em = 0.3
position_angle_ep = 0.3
postiion_angle_ref = "Wang2019ApJ...881..118W"
ellipticity = 0.29
ellipticity_em = 0.002
ellipticity_ep = 0.002
ellipticity_ref = "Wang2019ApJ...881..118W"
Mv = -13.393
Mv_em = 0.2
Mv_ep = 0.2
mv = 7.377
mv_em = 0.2
mv_ep = 0.2
mv_ref = "Munoz2018ApJ...860...66M"
rh = 19.9
rh_em = 0.06
rh_ep = 0.06
rh_ref = "Wang2019ApJ...881..118W"
metallicity = -1.07
metallicity_em = 0.01
metallicity_ep = 0.02
metallicity_ref = "Simon2019ARA&A..57..375S"
