ra = 202.0091
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 33.5521
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 210.86281499332887
distance_em = 5.7465971107722
distance_ep = 5.907595488640766
distance_modulus = 21.62
distance_modulus_em = 0.06
distance_modulus_ep = 0.06
distance_ref = "Kuehn2008ApJ...674L..81K"
pmra = -0.096
pmra_em = 0.031
pmra_ep = 0.03
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.116
pmdec_em = 0.02
pmdec_ep = 0.02
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 30.9
radial_velocity_em = 0.6
radial_velocity_ep = 0.6
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 7.6
sigma_v_em = 0.4
sigma_v_ep = 0.4
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = 80.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.44
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -8.73
Mv_em = 0.06
Mv_ep = 0.06
mv = 12.89
mv_em = 0.06
mv_ep = 0.06
ref_Mv = "Munoz2018ApJ...860...66M"
rh = 7.12
rh_em = 0.21
rh_ep = 0.21
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.91
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Simon2019ARA&A..57..375S"
pmra_gsr = 0.05988956705188869
pmdec_gsr = 0.06781136958362514
radial_velocity_gsr = 80.95863159670627
theta_pm_gsr = -39.64
