ra = 162.3436
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 51.0501
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 38.01893963205613
distance_em = 6.396163030372339
distance_ep = 7.689879329431292
distance_modulus = 17.9
distance_modulus_em = 0.4
distance_modulus_ep = 0.4
distance_ref = "Willman2006astro.ph..3486W"
pmra = 0.255
pmra_em = 0.087
pmra_ep = 0.077
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.11
pmdec_em = 0.091
pmdec_ep = 0.095
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -14.1
radial_velocity_em = 1.0
radial_velocity_ep = 1.0
radial_velocity_ref = "Willman2011AJ....142..128W"
sigma_v = 4.0
sigma_v_em = 0.8
sigma_v_ep = 0.8
sigma_v_ref = "Willman2011AJ....142..128W"
position_angle = 73.0
position_angle_em = 4.0
position_angle_ep = 4.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.47
ellipticity_em = 0.06
ellipticity_ep = 0.06
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -2.5299999999999994
Mv_em = 0.74
Mv_ep = 0.74
mv = 15.37
mv_em = 0.74
mv_ep = 0.74
mv_ref = "Munoz2018ApJ...860...66M"
rh = 2.51
rh_em = 0.22
rh_ep = 0.22
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.19
metallicity_em = 0.08
metallicity_ep = 0.08
metallicity_ref = "Willman2011AJ....142..128W"
