ra = 298.16875
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2024ApJ...967...72R"
dec = -22.06806
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2024ApJ...967...72R"
distance = 63.97348354826482
distance_em = 2.879281057707672
distance_ep = 3.014977393387902
distance_modulus = 19.03
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "Joo2019ApJ...875..120J"
pmra = -0.769
pmra_em = 0.035
pmra_ep = 0.035
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.903
pmdec_em = 0.023
pmdec_ep = 0.022
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -177.2
radial_velocity_em = 0.6
radial_velocity_ep = 0.5
radial_velocity_ref = "Longeard2021MNRAS.503.2754L"
sigma_v = 1.7
sigma_v_em = 0.5
sigma_v_ep = 0.5
sigma_v_ref = "Longeard2021MNRAS.503.2754L"
position_angle = 96.0
position_angle_em = 32.0
position_angle_ep = 50.0
postiion_angle_ref = "Richstein2024ApJ...967...72R"
ellipticity = 0.03
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Richstein2024ApJ...967...72R"
Mv = -5.210000000000001
Mv_em = 0.04
Mv_ep = 0.06
mv = 13.82
mv_em = 0.04
mv_ep = 0.06
mv_ref = "Richstein2024ApJ...967...72R"
rh = 1.85
rh_em = 0.07
rh_ep = 0.08
rh_ref = "Richstein2024ApJ...967...72R"
metallicity = -2.23
metallicity_em = 0.07
metallicity_ep = 0.07
metallicity_ref = "Longeard2021MNRAS.503.2754L"
