ra = 56.36
ra_em = 0.0
ra_ep = 0.0
ra_ref = "DrlicaWagner2015ApJ...813..109D"
dec = -60.45
dec_em = 0.0
dec_ep = 0.0
dec_ref = "DrlicaWagner2015ApJ...813..109D"
distance = 91.62204901219992
distance_em = 12.189225539771712
distance_ep = 14.05970190916571
distance_modulus = 19.81
distance_modulus_em = 0.31
distance_modulus_ep = 0.31
distance_ref = "DrlicaWagner2015ApJ...813..109D"
pmra = 0.26
pmra_em = 0.144
pmra_ep = 0.14
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.502
pmdec_em = 0.226
pmdec_ep = 0.222
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 274.2
radial_velocity_em = 7.45
radial_velocity_ep = 7.45
radial_velocity_ref = "Fritz2019A&A...623A.129F"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Fritz2019A&A...623A.129F"
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "DrlicaWagner2015ApJ...813..109D"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "DrlicaWagner2015ApJ...813..109D"
Mv = -3.299999999999997
Mv_em = 0.29
Mv_ep = 0.29
mv = 16.51
mv_em = 0.29
mv_ep = 0.29
mv_ref = "DrlicaWagner2015ApJ...813..109D"
rh = 2.4
rh_em = 0.8
rh_ep = 0.9
rh_ref = "DrlicaWagner2015ApJ...813..109D"
metallicity = -2.81
metallicity_em = 0.29
metallicity_ep = 0.29
metallicity_ref = "Fritz2019A&A...623A.129F"
