ra = 143.8079
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Ji2021ApJ...921...32J"
dec = -36.6991
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Ji2021ApJ...921...32J"
distance = 124.16523075924093
distance_em = 5.04102995650355
distance_ep = 5.254353385757696
distance_modulus = 20.47
distance_modulus_em = 0.09
distance_modulus_ep = 0.09
distance_ref = "Vivas2022ApJ...926...78V"
pmra = -0.093
pmra_em = 0.008
pmra_ep = 0.008
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.1
pmdec_em = 0.009
pmdec_ep = 0.009
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 288.8
radial_velocity_em = 0.4
radial_velocity_ep = 0.4
radial_velocity_ref = "Ji2021ApJ...921...32J"
sigma_v = 5.98
sigma_v_em = 0.36
sigma_v_ep = 0.37
sigma_v_ref = "Ji2021ApJ...921...32J"
position_angle = 156.0
position_angle_em = 2.4
position_angle_ep = 2.4
postiion_angle_ref = "Ji2021ApJ...921...32J"
ellipticity = 0.6
ellipticity_em = 0.04
ellipticity_ep = 0.04
ellipticity_ref = "Ji2021ApJ...921...32J"
Mv = -9.729999999999999
Mv_em = 0.08
Mv_ep = 0.08
mv = 10.74
mv_em = 0.08
mv_ep = 0.08
mv_ref = "Ji2021ApJ...921...32J"
rh = 104.6
rh_em = 8.6
rh_ep = 8.6
rh_ref = "Ji2021ApJ...921...32J"
metallicity = -1.9
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Ji2021ApJ...921...32J"
