ra = 19.47
ra_em = 0.0
ra_ep = 0.0
ra_ref = "DrlicaWagner2015ApJ...813..109D"
dec = -17.42
dec_em = 0.0
dec_ep = 0.0
dec_ref = "DrlicaWagner2015ApJ...813..109D"
distance = 29.922646366081892
distance_em = 2.5069046468030827
distance_ep = 2.7361368511517057
distance_modulus = 17.38
distance_modulus_em = 0.19
distance_modulus_ep = 0.19
distance_ref = "DrlicaWagner2015ApJ...813..109D"
pmra = 2.844
pmra_em = 0.059
pmra_ep = 0.061
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.474
pmdec_em = 0.063
pmdec_ep = 0.064
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "DrlicaWagner2015ApJ...813..109D"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "DrlicaWagner2015ApJ...813..109D"
Mv = 0.0
Mv_em = 0.68
Mv_ep = 0.68
mv = 17.38
mv_em = 0.68
mv_ep = 0.68
mv_ref = "DrlicaWagner2015ApJ...813..109D"
rh = 1.9
rh_em = 0.5
rh_ep = 1.0
rh_ref = "DrlicaWagner2015ApJ...813..109D"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
