ra = 153.268
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cicuendez2018A&A...609A..53C"
dec = -1.62
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cicuendez2018A&A...609A..53C"
distance = 85.90135215053961
distance_em = 3.8661977175578386
distance_ep = 4.0484060024640485
distance_modulus = 19.67
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "Lee2009ApJ...703..692L"
pmra = -0.409
pmra_em = 0.008
pmra_ep = 0.009
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.037
pmdec_em = 0.009
pmdec_ep = 0.009
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 224.3
radial_velocity_em = 0.1
radial_velocity_ep = 0.1
radial_velocity_ref = "Walker2009AJ....137.3100W"
sigma_v = 7.9
sigma_v_em = 1.3
sigma_v_ep = 1.3
sigma_v_ref = "Walker2009AJ....137.3100W"
position_angle = 52.0
position_angle_em = 3.0
position_angle_ep = 3.0
postiion_angle_ref = "Cicuendez2018A&A...609A..53C"
ellipticity = 0.27
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Cicuendez2018A&A...609A..53C"
Mv = -8.720000000000002
Mv_em = 0.06
Mv_ep = 0.06
mv = 10.95
mv_em = 0.06
mv_ep = 0.06
mv_ref = "Munoz2018ApJ...860...66M"
rh = 22.8
rh_em = 0.7
rh_ep = 0.7
rh_ref = "Cicuendez2018A&A...609A..53C"
metallicity = -1.97
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Simon2019ARA&A..57..375S"
