ra = 227.242
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 67.2221
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 70.14552984199713
distance_em = 2.847864213565316
distance_ep = 2.9683785063445924
distance_modulus = 19.23
distance_modulus_em = 0.09
distance_modulus_ep = 0.09
distance_ref = "Garofalo2024arXiv241012433G"
pmra = -0.12
pmra_em = 0.005
pmra_ep = 0.005
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.071
pmdec_em = 0.005
pmdec_ep = 0.005
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -247.0
radial_velocity_em = 0.4
radial_velocity_ep = 0.4
radial_velocity_ref = "Spencer2018AJ....156..257S"
sigma_v = 8.6
sigma_v_em = 0.3
sigma_v_ep = 0.3
sigma_v_ref = "Spencer2018AJ....156..257S"
position_angle = 50.0
position_angle_em = 1.0
position_angle_ep = 1.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.55
ellipticity_em = 0.01
ellipticity_ep = 0.01
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -8.860000000000001
Mv_em = 0.05
Mv_ep = 0.05
mv = 10.37
mv_em = 0.05
mv_ep = 0.05
mv_ref = "Munoz2018ApJ...860...66M"
rh = 18.3
rh_em = 0.11
rh_ep = 0.11
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.13
metallicity_em = 0.02
metallicity_ep = 0.02
metallicity_ref = "Pace2020MNRAS.495.3022P"
