ra = 185.4286
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = -31.9728
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 151.35612484362073
distance_em = 7.476267018036367
distance_ep = 7.864747861496255
distance_modulus = 20.9
distance_modulus_em = 0.11
distance_modulus_ep = 0.11
distance_ref = "Vivas2016AJ....151..118V"
pmra = -0.394
pmra_em = 0.14
pmra_ep = 0.14
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.0
pmdec_em = 0.104
pmdec_ep = 0.103
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 303.1
radial_velocity_em = 1.4
radial_velocity_ep = 1.4
radial_velocity_ref = "Kirby2015ApJ...810...56K"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Kirby2015ApJ...810...56K"
position_angle = 16.0
position_angle_em = 25.0
position_angle_ep = 25.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.24
ellipticity_em = 0.16
ellipticity_ep = 0.16
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -5.099999999999998
Mv_em = 0.22
Mv_ep = 0.11
mv = 15.8
mv_em = 0.22
mv_ep = 0.11
mv_ref = "Richstein2024ApJ...967...72R"
rh = 1.52
rh_em = 0.28
rh_ep = 0.28
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.02
metallicity_em = 0.08
metallicity_ep = 0.08
metallicity_ref = "Kirby2015ApJ...810...56K"
