ra = 34.8226
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 20.1624
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 36.475394692560734
distance_em = 2.434575722460643
distance_ep = 2.4291198068673125
distance_modulus = 17.81
distance_modulus_em = 0.15
distance_modulus_ep = 0.14
distance_ref = "Boettcher2013AJ....146...94B"
pmra = 1.446
pmra_em = 0.059
pmra_ep = 0.059
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.322
pmdec_em = 0.05
pmdec_ep = 0.049
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -40.2
radial_velocity_em = 0.9
radial_velocity_ep = 0.9
radial_velocity_ref = "Kirby2013ApJ...770...16K"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Kirby2013ApJ...770...16K"
position_angle = 164.0
position_angle_em = 14.0
position_angle_ep = 14.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.22
ellipticity_em = 0.07
ellipticity_ep = 0.07
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -1.9499999999999993
Mv_em = 0.88
Mv_ep = 0.88
mv = 15.86
mv_em = 0.88
mv_ep = 0.88
mv_ref = "Munoz2018ApJ...860...66M"
rh = 3.76
rh_em = 0.28
rh_ep = 0.28
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.22
metallicity_em = 0.13
metallicity_ep = 0.13
metallicity_ref = "Kirby2013ApJ...770...16K"
