ra = 0.717
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Simon2020ApJ...892..137S"
dec = -60.83
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Simon2020ApJ...892..137S"
distance = 46.98941086052151
distance_em = 3.7380277570206246
distance_ep = 4.061089137019138
distance_modulus = 18.36
distance_modulus_em = 0.18
distance_modulus_ep = 0.18
distance_ref = "Simon2020ApJ...892..137S"
pmra = 0.534
pmra_em = 0.053
pmra_ep = 0.05
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.707
pmdec_em = 0.055
pmdec_ep = 0.054
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 15.9
radial_velocity_em = 1.7
radial_velocity_ep = 1.8
radial_velocity_ref = "Simon2020ApJ...892..137S"
sigma_v = 4.3
sigma_v_em = 1.0
sigma_v_ep = 1.7
sigma_v_ref = "Simon2020ApJ...892..137S"
position_angle = 27.0
position_angle_em = 8.0
position_angle_ep = 9.0
postiion_angle_ref = "Simon2020ApJ...892..137S"
ellipticity = 0.39
ellipticity_em = 0.1
ellipticity_ep = 0.07
ellipticity_ref = "Simon2020ApJ...892..137S"
Mv = -3.0
Mv_em = 0.4
Mv_ep = 0.3
mv = 15.36
mv_em = 0.4
mv_ep = 0.3
mv_ref = "Simon2020ApJ...892..137S"
rh = 9.3
rh_em = 0.9
rh_ep = 1.4
rh_ref = "Simon2020ApJ...892..137S"
metallicity = -2.49
metallicity_em = 0.16
metallicity_ep = 0.15
metallicity_ref = "Simon2020ApJ...892..137S"
