ra = 331.025
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Simon2020ApJ...892..137S"
dec = -46.442
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Simon2020ApJ...892..137S"
distance = 55.20774392807573
distance_em = 2.484757785793512
distance_ep = 2.6018608124961418
distance_modulus = 18.71
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "MartinezVazquez2019MNRAS.490.2183M"
pmra = 0.384
pmra_em = 0.033
pmra_ep = 0.033
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.484
pmdec_em = 0.04
pmdec_ep = 0.039
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -110.0
radial_velocity_em = 0.5
radial_velocity_ep = 0.5
radial_velocity_ref = "Simon2020ApJ...892..137S"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Simon2020ApJ...892..137S"
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "Simon2020ApJ...892..137S"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Simon2020ApJ...892..137S"
Mv = -3.5
Mv_em = 0.3
Mv_ep = 0.3
mv = 15.21
mv_em = 0.3
mv_ep = 0.3
mv_ref = "Simon2020ApJ...892..137S"
rh = 5.9
rh_em = 0.5
rh_ep = 0.5
rh_ref = "Simon2020ApJ...892..137S"
metallicity = -2.51
metallicity_em = 0.11
metallicity_ep = 0.11
metallicity_ref = "Simon2020ApJ...892..137S"
