ra = 359.1075
ra_em = 0.0
ra_ep = 0.0
ra_ref = "MutluPakdil2018ApJ...863...25M"
dec = -59.58332
dec_em = 0.0
dec_ep = 0.0
dec_ref = "MutluPakdil2018ApJ...863...25M"
distance = 22.90867652767775
distance_em = 1.031060288182232
distance_ep = 1.0796526625172014
distance_modulus = 16.8
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "MutluPakdil2018ApJ...863...25M"
pmra = -0.048
pmra_em = 0.036
pmra_ep = 0.035
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.638
pmdec_em = 0.039
pmdec_ep = 0.039
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -102.3
radial_velocity_em = 0.4
radial_velocity_ep = 0.4
radial_velocity_ref = "Simon2017ApJ...838...11S"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Simon2017ApJ...838...11S"
position_angle = 25.0
position_angle_em = 38.0
position_angle_ep = 38.0
postiion_angle_ref = "MutluPakdil2018ApJ...863...25M"
ellipticity = 0.2
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "MutluPakdil2018ApJ...863...25M"
Mv = -1.3000000000000007
Mv_em = 0.2
Mv_ep = 0.2
mv = 15.5
mv_em = 0.2
mv_ep = 0.2
mv_ref = "MutluPakdil2018ApJ...863...25M"
rh = 5.1
rh_em = 1.2
rh_ep = 1.2
rh_ref = "MutluPakdil2018ApJ...863...25M"
metallicity = -2.42
metallicity_em = 0.08
metallicity_ep = 0.07
metallicity_ref = "Simon2017ApJ...838...11S"
