ra = 338.4813
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Torrealba2016MNRAS.463..712T"
dec = -9.3274
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Torrealba2016MNRAS.463..712T"
distance = 107.64652136298349
distance_em = 3.4147784236531322
distance_ep = 3.5266513651757094
distance_modulus = 20.16
distance_modulus_em = 0.07
distance_modulus_ep = 0.07
distance_ref = "Torrealba2016MNRAS.463..712T"
pmra = -0.179
pmra_em = 0.113
pmra_ep = 0.119
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.466
pmdec_em = 0.095
pmdec_ep = 0.096
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -65.3
radial_velocity_em = 1.8
radial_velocity_ep = 1.8
radial_velocity_ref = "Bruce2023ApJ...950..167B"
sigma_v = 4.7
sigma_v_em = 1.2
sigma_v_ep = 1.8
sigma_v_ref = "Bruce2023ApJ...950..167B"
position_angle = 121.0
position_angle_em = 9.0
position_angle_ep = 9.0
postiion_angle_ref = "Torrealba2016MNRAS.463..712T"
ellipticity = 0.39
ellipticity_em = 0.09
ellipticity_ep = 0.09
ellipticity_ref = "Torrealba2016MNRAS.463..712T"
Mv = -4.359999999999999
Mv_em = 0.14
Mv_ep = 0.14
mv = 15.8
mv_em = 0.14
mv_ep = 0.14
mv_ref = "Torrealba2016MNRAS.463..712T"
rh = 5.1
rh_em = 0.8
rh_ep = 0.8
rh_ref = "Torrealba2016MNRAS.463..712T"
metallicity = -2.57
metallicity_em = 0.17
metallicity_ep = 0.17
metallicity_ref = "Bruce2023ApJ...950..167B"
