ra = 189.585
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Mau2020ApJ...890..136M"
dec = -40.902
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Mau2020ApJ...890..136M"
distance = 117.70637907805695
distance_em = 3.7338986760820916
distance_ep = 3.856226445680889
distance_modulus = 20.354
distance_modulus_em = 0.07
distance_modulus_ep = 0.07
distance_ref = "MartinezVazquez2021AJ....162..253M"
pmra = -0.14
pmra_em = 0.05
pmra_ep = 0.05
pmra_ref = "Heiger2024ApJ...961..234H"
pmdec = -0.19
pmdec_em = 0.04
pmdec_ep = 0.04
pmdec_ref = "Heiger2024ApJ...961..234H"
radial_velocity = 44.8
radial_velocity_em = 0.8
radial_velocity_ep = 0.8
radial_velocity_ref = "Heiger2024ApJ...961..234H"
sigma_v = 4.2
sigma_v_em = 0.5
sigma_v_ep = 0.6
sigma_v_ref = "Heiger2024ApJ...961..234H"
position_angle = 20.0
position_angle_em = 11.0
position_angle_ep = 11.0
postiion_angle_ref = "Mau2020ApJ...890..136M"
ellipticity = 0.4
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Mau2020ApJ...890..136M"
Mv = -5.574
Mv_em = 0.11
Mv_ep = 0.11
mv = 14.78
mv_em = 0.11
mv_ep = 0.11
mv_ref = "Mau2020ApJ...890..136M"
rh = 2.9
rh_em = 0.4
rh_ep = 0.5
rh_ref = "Mau2020ApJ...890..136M"
metallicity = -2.57
metallicity_em = 0.08
metallicity_ep = 0.08
metallicity_ref = "Heiger2024ApJ...961..234H"
