ra = 342.9796
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Koposov2015ApJ...805..130K"
dec = -58.5689
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Koposov2015ApJ...805..130K"
distance = 56.23413251903491
distance_em = 4.947994119898432
distance_ep = 5.4253676671133135
distance_modulus = 18.75
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Vivas2020ApJS..247...35V"
pmra = 0.911
pmra_em = 0.026
pmra_ep = 0.024
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.28
pmdec_em = 0.029
pmdec_ep = 0.029
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -124.7
radial_velocity_em = 1.0
radial_velocity_ep = 1.0
radial_velocity_ref = "Chiti2023AJ....165...55C"
sigma_v = 3.8
sigma_v_em = 0.7
sigma_v_ep = 1.1
sigma_v_ref = "Chiti2023AJ....165...55C"
position_angle = 107.0
position_angle_em = 18.0
position_angle_ep = 18.0
postiion_angle_ref = "Koposov2015ApJ...805..130K"
ellipticity = 0.39
ellipticity_em = 0.2
ellipticity_ep = 0.1
ellipticity_ref = "Koposov2015ApJ...805..130K"
Mv = -3.75
Mv_em = 0.1
Mv_ep = 0.1
mv = 15.0
mv_em = 0.1
mv_ep = 0.1
mv_ref = "Koposov2015ApJ...805..130K"
rh = 12.89
rh_em = 1.98
rh_ep = 1.71
rh_ref = "Koposov2015ApJ...805..130K"
metallicity = -2.77
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = "Chiti2021NatAs...5..392C"
