ra = 336.1074167
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2022ApJ...933..217R"
dec = 5.4150472
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2022ApJ...933..217R"
distance = 214.7830474130533
distance_em = 11.547346319431199
distance_ep = 12.203437775328808
distance_modulus = 21.66
distance_modulus_em = 0.12
distance_modulus_ep = 0.12
distance_ref = "Kim2016ApJ...833...16K"
pmra = -0.03
pmra_em = 0.21
pmra_ep = 0.21
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.58
pmdec_em = 0.208
pmdec_ep = 0.213
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -222.9
radial_velocity_em = 2.6
radial_velocity_ep = 2.6
radial_velocity_ref = "Kim2016ApJ...833...16K"
sigma_v = 5.4
sigma_v_em = 2.5
sigma_v_ep = 3.0
sigma_v_ref = "Kim2016ApJ...833...16K"
position_angle = 83.0
position_angle_em = 7.0
position_angle_ep = 8.0
postiion_angle_ref = "Richstein2022ApJ...933..217R"
ellipticity = 0.37
ellipticity_em = 0.09
ellipticity_ep = 0.08
ellipticity_ref = "Richstein2022ApJ...933..217R"
Mv = -4.170000000000002
Mv_em = 0.22
Mv_ep = 0.19
mv = 17.49
mv_em = 0.22
mv_ep = 0.19
mv_ref = "Richstein2022ApJ...933..217R"
rh = 1.67
rh_em = 0.21
rh_ep = 0.26
rh_ref = "Richstein2022ApJ...933..217R"
metallicity = -2.55
metallicity_em = 0.15
metallicity_ep = 0.15
metallicity_ref = "Kim2016ApJ...833...16K"
