ra = 53.9203
ra_em = 0.0
ra_ep = 0.0
ra_ref = "MutluPakdil2018ApJ...863...25M"
dec = -54.0513
dec_em = 0.0
dec_ep = 0.0
dec_ref = "MutluPakdil2018ApJ...863...25M"
distance = 31.622776601683793
distance_em = 1.4232593976636636
distance_ep = 1.4903355465753556
distance_modulus = 17.5
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "MutluPakdil2018ApJ...863...25M"
pmra = 2.377
pmra_em = 0.024
pmra_ep = 0.023
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.379
pmdec_em = 0.025
pmdec_ep = 0.026
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 64.3
radial_velocity_em = 1.2
radial_velocity_ep = 1.2
radial_velocity_ref = "Walker2015ApJ...808..108W"
sigma_v = 3.6
sigma_v_em = 0.7
sigma_v_ep = 1.0
sigma_v_ref = "Walker2015ApJ...808..108W"
position_angle = 68.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "MutluPakdil2018ApJ...863...25M"
ellipticity = 0.6
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "MutluPakdil2018ApJ...863...25M"
Mv = -3.0999999999999996
Mv_em = 0.1
Mv_ep = 0.1
mv = 14.4
mv_em = 0.1
mv_ep = 0.1
mv_ref = "MutluPakdil2018ApJ...863...25M"
rh = 6.3
rh_em = 0.4
rh_ep = 0.4
rh_ref = "MutluPakdil2018ApJ...863...25M"
metallicity = -2.65
metallicity_em = 0.07
metallicity_ep = 0.07
metallicity_ref = "Simon2015ApJ...808...95S"
