ra = 238.1983333
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Longeard2018MNRAS.480.2609L"
dec = 64.56527778
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Longeard2018MNRAS.480.2609L"
distance = 21.57744409152669
distance_em = 0.49116259219380254
distance_ep = 0.5026032386623207
distance_modulus = 16.67
distance_modulus_em = 0.05
distance_modulus_ep = 0.05
distance_ref = "Longeard2018MNRAS.480.2609L"
pmra = 1.027
pmra_em = 0.065
pmra_ep = 0.067
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.887
pmdec_em = 0.072
pmdec_ep = 0.072
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -342.5
radial_velocity_em = 1.2
radial_velocity_ep = 1.1
radial_velocity_ref = "Longeard2018MNRAS.480.2609L"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Longeard2018MNRAS.480.2609L"
position_angle = 76.0
position_angle_em = 32.0
position_angle_ep = 22.0
postiion_angle_ref = "Longeard2018MNRAS.480.2609L"
ellipticity = 0.23
ellipticity_em = 0.15
ellipticity_ep = 0.15
ellipticity_ref = "Longeard2018MNRAS.480.2609L"
Mv = -0.8000000000000025
Mv_em = 1.0
Mv_ep = 0.4
mv = 15.87
mv_em = 1.0
mv_ep = 0.4
mv_ref = "Longeard2018MNRAS.480.2609L"
rh = 3.0
rh_em = 0.5
rh_ep = 0.7
rh_ref = "Longeard2018MNRAS.480.2609L"
metallicity = -2.7
metallicity_em = 0.1
metallicity_ep = 0.1
metallicity_ref = "Longeard2018MNRAS.480.2609L"
