ra = 158.7706
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 51.9479
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 97.27472237769662
distance_em = 5.652673365496511
distance_ep = 6.00141819844319
distance_modulus = 19.94
distance_modulus_em = 0.13
distance_modulus_ep = 0.13
distance_ref = "Garofalo2013ApJ...767...62G"
pmra = -0.401
pmra_em = 0.036
pmra_ep = 0.036
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.613
pmdec_em = 0.042
pmdec_ep = 0.04
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -55.3
radial_velocity_em = 1.4
radial_velocity_ep = 1.4
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 7.0
sigma_v_em = 1.0
sigma_v_ep = 1.0
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = 67.0
position_angle_em = 2.0
position_angle_ep = 2.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.59
ellipticity_em = 0.03
ellipticity_ep = 0.03
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -5.140000000000001
Mv_em = 0.38
Mv_ep = 0.38
mv = 14.8
mv_em = 0.38
mv_ep = 0.38
mv_ref = "Munoz2018ApJ...860...66M"
rh = 8.31
rh_em = 0.35
rh_ep = 0.35
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.16
metallicity_em = 0.13
metallicity_ep = 0.11
metallicity_ref = "Simon2019ARA&A..57..375S"
