ra = 344.166
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cantu2021ApJ...916...81C"
dec = -50.168
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cantu2021ApJ...916...81C"
distance = 126.47363474711523
distance_em = 5.692251236437258
distance_ep = 5.960518772351463
distance_modulus = 20.51
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "MartinezVazquez2019MNRAS.490.2183M"
pmra = 0.069
pmra_em = 0.05
pmra_ep = 0.051
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.248
pmdec_em = 0.072
pmdec_ep = 0.071
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -143.5
radial_velocity_em = 1.2
radial_velocity_ep = 1.2
radial_velocity_ref = "Chiti2022ApJ...939...41C"
sigma_v = 2.5
sigma_v_em = 0.8
sigma_v_ep = 1.3
sigma_v_ref = "Chiti2022ApJ...939...41C"
position_angle = 153.0
position_angle_em = 7.0
position_angle_ep = 8.0
postiion_angle_ref = "Cantu2021ApJ...916...81C"
ellipticity = 0.44
ellipticity_em = 0.1
ellipticity_ep = 0.08
ellipticity_ref = "Cantu2021ApJ...916...81C"
Mv = -4.130000000000003
Mv_em = 0.3
Mv_ep = 0.3
mv = 16.38
mv_em = 0.3
mv_ep = 0.3
mv_ref = "Cantu2021ApJ...916...81C"
rh = 4.16
rh_em = 0.74
rh_ep = 0.54
rh_ref = "Cantu2021ApJ...916...81C"
metallicity = -2.62
metallicity_em = 0.11
metallicity_ep = 0.11
metallicity_ref = "Chiti2022ApJ...939...41C"
