ra = 151.7504
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 16.0756
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 22.90867652767775
distance_em = 2.0157152191373378
distance_ep = 2.210187787418075
distance_modulus = 16.8
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Belokurov2007ApJ...654..897B"
pmra = -2.102
pmra_em = 0.051
pmra_ep = 0.051
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -3.375
pmdec_em = 0.046
pmdec_ep = 0.044
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 208.5
radial_velocity_em = 0.9
radial_velocity_ep = 0.9
radial_velocity_ref = "Simon2011ApJ...733...46S"
sigma_v = 3.7
sigma_v_em = 1.1
sigma_v_ep = 1.4
sigma_v_ref = "Simon2011ApJ...733...46S"
position_angle = 77.0
position_angle_em = 15.0
position_angle_ep = 15.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.33
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -1.3000000000000007
Mv_em = 0.73
Mv_ep = 0.73
mv = 15.5
mv_em = 0.73
mv_ep = 0.73
mv_ref = "Munoz2018ApJ...860...66M"
rh = 3.62
rh_em = 0.42
rh_ep = 0.42
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.5
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = "Simon2011ApJ...733...46S"
