ra = 344.6364583
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Richstein2022ApJ...933..217R"
dec = 5.9555444
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Richstein2022ApJ...933..217R"
distance = 182.8100216142741
distance_em = 13.76592844994775
distance_ep = 14.886942396912104
distance_modulus = 21.31
distance_modulus_em = 0.17
distance_modulus_ep = 0.17
distance_ref = "Sand2012ApJ...756...79S"
pmra = 0.681
pmra_em = 0.307
pmra_ep = 0.309
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.645
pmdec_em = 0.209
pmdec_ep = 0.215
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -226.5
radial_velocity_em = 2.7
radial_velocity_ep = 2.7
radial_velocity_ref = "Kirby2015ApJ...810...56K"
sigma_v = 5.4
sigma_v_em = 2.4
sigma_v_ep = 3.6
sigma_v_ref = "Kirby2015ApJ...810...56K"
position_angle = 98.0
position_angle_em = 3.0
position_angle_ep = 3.0
postiion_angle_ref = "Richstein2022ApJ...933..217R"
ellipticity = 0.37
ellipticity_em = 0.03
ellipticity_ep = 0.04
ellipticity_ref = "Richstein2022ApJ...933..217R"
Mv = -4.279999999999998
Mv_em = 0.16
Mv_ep = 0.19
mv = 17.03
mv_em = 0.16
mv_ep = 0.19
mv_ref = "Richstein2022ApJ...933..217R"
rh = 1.34
rh_em = 0.07
rh_ep = 0.08
rh_ref = "Richstein2022ApJ...933..217R"
metallicity = -2.45
metallicity_em = 0.07
metallicity_ep = 0.07
metallicity_ref = "Kirby2015ApJ...810...56K"
