ra = 177.31
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Torrealba2016MNRAS.459.2370T"
dec = -18.413
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Torrealba2016MNRAS.459.2370T"
distance = 116.5735440441268
distance_em = 3.6979627203032237
distance_ep = 3.819113177473838
distance_modulus = 20.333
distance_modulus_em = 0.07
distance_modulus_ep = 0.07
distance_ref = "Torrealba2016MNRAS.459.2370T"
pmra = -0.072
pmra_em = 0.02
pmra_ep = 0.02
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.112
pmdec_em = 0.013
pmdec_ep = 0.013
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 89.3
radial_velocity_em = 0.3
radial_velocity_ep = 0.3
radial_velocity_ref = "Ji2021ApJ...921...32J"
sigma_v = 2.34
sigma_v_em = 0.3
sigma_v_ep = 0.42
sigma_v_ref = "Ji2021ApJ...921...32J"
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "Torrealba2016MNRAS.459.2370T"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Torrealba2016MNRAS.459.2370T"
Mv = -8.182999999999998
Mv_em = 0.1
Mv_ep = 0.1
mv = 12.15
mv_em = 0.1
mv_ep = 0.1
mv_ref = "Torrealba2016MNRAS.459.2370T"
rh = 31.2
rh_em = 2.5
rh_ep = 2.5
rh_ref = "Torrealba2016MNRAS.459.2370T"
metallicity = -2.16
metallicity_em = 0.04
metallicity_ep = 0.04
metallicity_ref = "Ji2021ApJ...921...32J"
