ra = 260.0684
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 57.9185
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 81.54550000611157
distance_em = 1.4883731125754025
distance_ep = 1.5160440346806183
distance_modulus = 19.557
distance_modulus_em = 0.04
distance_modulus_ep = 0.04
distance_ref = "Bhardwaj2024AJ....167..247B"
pmra = 0.044
pmra_em = 0.006
pmra_ep = 0.005
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.188
pmdec_em = 0.006
pmdec_ep = 0.006
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -290.7
radial_velocity_em = 0.75
radial_velocity_ep = 0.75
radial_velocity_ref = "Walker2015MNRAS.448.2717W"
sigma_v = 9.1
sigma_v_em = 1.2
sigma_v_ep = 1.2
sigma_v_ref = "Walker2015MNRAS.448.2717W"
position_angle = 87.0
position_angle_em = 1.0
position_angle_ep = 1.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.29
ellipticity_em = 0.01
ellipticity_ep = 0.01
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -8.866999999999999
Mv_em = 0.05
Mv_ep = 0.05
mv = 10.69
mv_em = 0.05
mv_ep = 0.05
mv_ref = "Munoz2018ApJ...860...66M"
rh = 9.67
rh_em = 0.09
rh_ep = 0.09
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.0
metallicity_em = 0.02
metallicity_ep = 0.02
metallicity_ref = "Simon2019ARA&A..57..375S"
