ra = 114.1066
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Torrealba2018MNRAS.475.5085T"
dec = -57.9991
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Torrealba2018MNRAS.475.5085T"
distance = 37.39383436431516
distance_em = 0.39398124702920256
distance_ep = 0.3981764318727343
distance_modulus = 17.864
distance_modulus_em = 0.023
distance_modulus_ep = 0.023
distance_ref = "Torrealba2018MNRAS.475.5085T"
pmra = 1.885
pmra_em = 0.019
pmra_ep = 0.018
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.133
pmdec_em = 0.019
pmdec_ep = 0.019
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 477.2
radial_velocity_em = 1.2
radial_velocity_ep = 1.2
radial_velocity_ref = "Li2018ApJ...857..145L"
sigma_v = 3.4
sigma_v_em = 0.8
sigma_v_ep = 1.2
sigma_v_ref = "Li2018ApJ...857..145L"
position_angle = 170.0
position_angle_em = 9.0
position_angle_ep = 9.0
postiion_angle_ref = "Torrealba2018MNRAS.475.5085T"
ellipticity = 0.34
ellipticity_em = 0.07
ellipticity_ep = 0.07
ellipticity_ref = "Torrealba2018MNRAS.475.5085T"
Mv = -4.574000000000002
Mv_em = 0.1
Mv_ep = 0.1
mv = 13.29
mv_em = 0.1
mv_ep = 0.1
mv_ref = "Torrealba2018MNRAS.475.5085T"
rh = 8.69
rh_em = 0.75
rh_ep = 0.75
rh_ref = "Torrealba2018MNRAS.475.5085T"
metallicity = -2.44
metallicity_em = 0.09
metallicity_ep = 0.09
metallicity_ref = "Li2018ApJ...857..145L"
