ra = 31.331
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Homma2018PASJ...70S..18H"
dec = -4.27
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Homma2018PASJ...70S..18H"
distance = 251.1886431509582
distance_em = 22.10187787418073
distance_ep = 24.23422718285812
distance_modulus = 22.0
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Homma2024PASJ...76..733H"
pmra = nan
pmra_em = nan
pmra_ep = nan
pmra_ref = nan
pmdec = nan
pmdec_em = nan
pmdec_ep = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 101.0
position_angle_em = 6.0
position_angle_ep = 5.0
postiion_angle_ref = "Homma2018PASJ...70S..18H"
ellipticity = 0.76
ellipticity_em = 0.08
ellipticity_ep = 0.06
ellipticity_ref = "Homma2018PASJ...70S..18H"
Mv = -3.4499999999999993
Mv_em = 0.43
Mv_ep = 0.49
mv = 18.55
mv_em = 0.43
mv_ep = 0.49
mv_ref = "Homma2024PASJ...76..733H"
rh = 1.23
rh_em = 0.19
rh_ep = 0.42
rh_ref = "Homma2018PASJ...70S..18H"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
