ra = 152.1146
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 12.3059
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 258.22601906345955
distance_em = 9.3402872352205
distance_ep = 9.690813418443042
distance_modulus = 22.06
distance_modulus_em = 0.08
distance_modulus_ep = 0.08
distance_ref = "Stetson2014PASP..126..616S"
pmra = -0.111
pmra_em = 0.004
pmra_ep = 0.004
pmra_ref = "Bennet2024ApJ...971...98B"
pmdec = -0.063
pmdec_em = 0.005
pmdec_ep = 0.005
pmdec_ref = "Bennet2024ApJ...971...98B"
radial_velocity = 282.9
radial_velocity_em = 0.5
radial_velocity_ep = 0.5
radial_velocity_ref = "Mateo2008ApJ...675..201M"
sigma_v = 9.2
sigma_v_em = 0.4
sigma_v_ep = 0.4
sigma_v_ref = "Mateo2008ApJ...675..201M"
position_angle = 78.0
position_angle_em = 1.0
position_angle_ep = 1.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.3
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -11.819999999999999
Mv_em = 0.28
Mv_ep = 0.28
mv = 10.24
mv_em = 0.28
mv_ep = 0.28
mv_ref = "Munoz2018ApJ...860...66M"
rh = 3.65
rh_em = 0.03
rh_ep = 0.03
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.48
metallicity_em = 0.01
metallicity_ep = 0.02
metallicity_ref = "Simon2019ARA&A..57..375S"
