ra = 186.7454
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 23.9069
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 42.26686142656025
distance_em = 1.5288336461489394
distance_ep = 1.5862083509382714
distance_modulus = 18.13
distance_modulus_em = 0.08
distance_modulus_ep = 0.08
distance_ref = "Musella2009ApJ...695L..83M"
pmra = 0.423
pmra_em = 0.027
pmra_ep = 0.026
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -1.721
pmdec_em = 0.024
pmdec_ep = 0.024
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 98.1
radial_velocity_em = 0.9
radial_velocity_ep = 0.9
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 4.6
sigma_v_em = 0.8
sigma_v_ep = 0.8
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = -57.0
position_angle_em = 4.0
position_angle_ep = 4.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.37
ellipticity_em = 0.05
ellipticity_ep = 0.05
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -4.289999999999999
Mv_em = 0.25
Mv_ep = 0.25
mv = 13.84
mv_em = 0.25
mv_ep = 0.25
mv_ref = "Munoz2018ApJ...860...66M"
rh = 5.64
rh_em = 0.3
rh_ep = 0.3
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.43
metallicity_em = 0.11
metallicity_ep = 0.11
metallicity_ref = "Simon2019ARA&A..57..375S"
