ra = 101.18
ra_em = 0.0
ra_ep = 0.0
ra_ref = "DrlicaWagner2016ApJ...833L...5D"
dec = -59.897
dec_em = 0.0
dec_ep = 0.0
dec_ref = "DrlicaWagner2016ApJ...833L...5D"
distance = 45.708818961487516
distance_em = 3.050867081328171
distance_ep = 2.5970612424897723
distance_modulus = 18.3
distance_modulus_em = 0.15
distance_modulus_ep = 0.12
distance_ref = "DrlicaWagner2016ApJ...833L...5D"
pmra = 1.15
pmra_em = 0.06
pmra_ep = 0.06
pmra_ref = "Battaglia2022A&A...657A..54B"
pmdec = 1.14
pmdec_em = 0.05
pmdec_ep = 0.06
pmdec_ref = "Battaglia2022A&A...657A..54B"
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 14.0
position_angle_em = 66.0
position_angle_ep = 60.0
postiion_angle_ref = "DrlicaWagner2016ApJ...833L...5D"
ellipticity = 0.13
ellipticity_em = 0.13
ellipticity_ep = 0.22
ellipticity_ref = "DrlicaWagner2016ApJ...833L...5D"
Mv = -3.200000000000001
Mv_em = 0.5
Mv_ep = 0.4
mv = 15.1
mv_em = 0.5
mv_ep = 0.4
mv_ref = "DrlicaWagner2016ApJ...833L...5D"
rh = 3.8
rh_em = 1.0
rh_ep = 1.5
rh_ref = "DrlicaWagner2016ApJ...833L...5D"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
