ra = 209.3
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Moskowitz2020ApJ...892...27M"
dec = 26.8
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Moskowitz2020ApJ...892...27M"
distance = 46.55860935229591
distance_em = 0.42685189625800035
distance_ep = 0.43080150822559915
distance_modulus = 18.34
distance_modulus_em = 0.02
distance_modulus_ep = 0.02
distance_ref = "Carlin2018ApJ...865....7C"
pmra = -1.176
pmra_em = 0.019
pmra_ep = 0.019
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.89
pmdec_em = 0.015
pmdec_ep = 0.015
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 197.5
radial_velocity_em = 3.6
radial_velocity_ep = 3.6
radial_velocity_ref = "Carlin2009ApJ...702L...9C"
sigma_v = 10.7
sigma_v_em = 3.5
sigma_v_ep = 3.5
sigma_v_ref = "Carlin2009ApJ...702L...9C"
position_angle = 279.0
position_angle_em = 9.0
position_angle_ep = 7.0
postiion_angle_ref = "Moskowitz2020ApJ...892...27M"
ellipticity = 0.33
ellipticity_em = 0.09
ellipticity_ep = 0.08
ellipticity_ref = "Moskowitz2020ApJ...892...27M"
Mv = -5.74
Mv_em = 0.5
Mv_ep = 0.5
mv = 12.6
mv_em = 0.5
mv_ep = 0.5
mv_ref = "Correnti2009MNRAS.397L..26C"
rh = 40.6
rh_em = 3.8
rh_ep = 4.2
rh_ref = "Moskowitz2020ApJ...892...27M"
metallicity = -2.1
metallicity_em = 0.2
metallicity_ep = 0.2
metallicity_ref = "Carlin2009ApJ...702L...9C"
