ra = 114.6298
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Torrealba2018MNRAS.475.5085T"
dec = -57.8997
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Torrealba2018MNRAS.475.5085T"
distance = 27.797132677592884
distance_em = 1.25107705783752
distance_ep = 1.3100385030731978
distance_modulus = 17.22
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "Torrealba2018MNRAS.475.5085T"
pmra = 3.095
pmra_em = 0.041
pmra_ep = 0.04
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 1.395
pmdec_em = 0.045
pmdec_ep = 0.045
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 284.6
radial_velocity_em = 3.1
radial_velocity_ep = 3.4
radial_velocity_ref = "Li2018ApJ...857..145L"
sigma_v = 5.6
sigma_v_em = 2.1
sigma_v_ep = 4.3
sigma_v_ref = "Li2018ApJ...857..145L"
position_angle = 150.0
position_angle_em = 14.0
position_angle_ep = 14.0
postiion_angle_ref = "Torrealba2018MNRAS.475.5085T"
ellipticity = 0.55
ellipticity_em = 0.18
ellipticity_ep = 0.18
ellipticity_ref = "Torrealba2018MNRAS.475.5085T"
Mv = -2.3999999999999986
Mv_em = 0.2
Mv_ep = 0.2
mv = 14.82
mv_em = 0.2
mv_ep = 0.2
mv_ref = "Torrealba2018MNRAS.475.5085T"
rh = 3.75
rh_em = 1.0
rh_ep = 1.0
rh_ref = "Torrealba2018MNRAS.475.5085T"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
