ra = 194.2927
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 34.3226
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 159.9558028614668
distance_em = 4.359239700959279
distance_ep = 4.481369460026087
distance_modulus = 21.02
distance_modulus_em = 0.06
distance_modulus_ep = 0.06
distance_ref = "Greco2008ApJ...675L..73G"
pmra = -0.124
pmra_em = 0.115
pmra_ep = 0.117
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.254
pmdec_em = 0.08
pmdec_ep = 0.082
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = -128.9
radial_velocity_em = 1.2
radial_velocity_ep = 1.2
radial_velocity_ref = "Simon2007ApJ...670..313S"
sigma_v = 4.6
sigma_v_em = 0.8
sigma_v_ep = 0.8
sigma_v_ref = "Simon2007ApJ...670..313S"
position_angle = 9.0
position_angle_em = 15.0
position_angle_ep = 15.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.4
ellipticity_em = 0.13
ellipticity_ep = 0.13
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -5.17
Mv_em = 0.32
Mv_ep = 0.32
mv = 15.85
mv_em = 0.32
mv_ep = 0.32
mv_ref = "Munoz2018ApJ...860...66M"
rh = 1.52
rh_em = 0.24
rh_ep = 0.24
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -2.35
metallicity_em = 0.19
metallicity_ep = 0.16
metallicity_ref = "Simon2019ARA&A..57..375S"
