ra = 56.0925
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Crnojevic2016ApJ...824L..14C"
dec = -43.5329
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Crnojevic2016ApJ...824L..14C"
distance = 369.8281797802659
distance_em = 8.418317140652732
distance_ep = 8.614404936827668
distance_modulus = 22.84
distance_modulus_em = 0.05
distance_modulus_ep = 0.05
distance_ref = "MartinezVazquez2021MNRAS.508.1064M"
pmra = 0.125
pmra_em = 0.1
pmra_ep = 0.101
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.013
pmdec_em = 0.127
pmdec_ep = 0.123
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 75.6
radial_velocity_em = 1.3
radial_velocity_ep = 1.3
radial_velocity_ref = "Li2017ApJ...838....8L"
sigma_v = 6.9
sigma_v_em = 0.9
sigma_v_ep = 1.2
sigma_v_ref = "Li2017ApJ...838....8L"
position_angle = 72.6
position_angle_em = 3.3
position_angle_ep = 3.3
postiion_angle_ref = "Crnojevic2016ApJ...824L..14C"
ellipticity = 0.48
ellipticity_em = 0.04
ellipticity_ep = 0.04
ellipticity_ref = "Crnojevic2016ApJ...824L..14C"
Mv = -7.119999999999999
Mv_em = 0.3
Mv_ep = 0.3
mv = 15.72
mv_em = 0.3
mv_ep = 0.3
mv_ref = "Crnojevic2016ApJ...824L..14C"
rh = 2.31
rh_em = 0.12
rh_ep = 0.12
rh_ref = "Crnojevic2016ApJ...824L..14C"
metallicity = -2.38
metallicity_em = 0.13
metallicity_ep = 0.13
metallicity_ref = "Li2017ApJ...838....8L"
