ra = 82.85696
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Carlin2017AJ....154..267C"
dec = -28.04253
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Carlin2017AJ....154..267C"
distance = 182.8100216142741
distance_em = 9.029938739336473
distance_ep = 9.499151276741685
distance_modulus = 21.31
distance_modulus_em = 0.11
distance_modulus_ep = 0.11
distance_ref = "Carlin2017AJ....154..267C"
pmra = 0.169
pmra_em = 0.073
pmra_ep = 0.071
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = -0.4
pmdec_em = 0.079
pmdec_ep = 0.079
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = 153.7
radial_velocity_em = 4.9
radial_velocity_ep = 4.9
radial_velocity_ref = "Fritz2019A&A...623A.129F"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Fritz2019A&A...623A.129F"
position_angle = 24.0
position_angle_em = 9.0
position_angle_ep = 9.0
postiion_angle_ref = "Carlin2017AJ....154..267C"
ellipticity = 0.3
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Carlin2017AJ....154..267C"
Mv = -4.199999999999999
Mv_em = 0.2
Mv_ep = 0.2
mv = 17.11
mv_em = 0.2
mv_ep = 0.2
mv_ref = "Carlin2017AJ....154..267C"
rh = 2.2
rh_em = 0.2
rh_ep = 0.2
rh_ref = "Carlin2017AJ....154..267C"
metallicity = -2.37
metallicity_em = 0.34
metallicity_ep = 0.35
metallicity_ref = "Fritz2019A&A...623A.129F"
