ra = 168.3627
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = 22.1529
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 233.34580622810043
distance_em = 13.559818949617664
distance_ep = 14.396399535228198
distance_modulus = 21.84
distance_modulus_em = 0.13
distance_modulus_ep = 0.13
distance_ref = "Bellazzini2005MNRAS.360..185B"
pmra = -0.13
pmra_em = 0.009
pmra_ep = 0.009
pmra_ref = "Bennet2024ApJ...971...98B"
pmdec = -0.143
pmdec_em = 0.009
pmdec_ep = 0.009
pmdec_ref = "Bennet2024ApJ...971...98B"
radial_velocity = 78.5
radial_velocity_em = 0.6
radial_velocity_ep = 0.6
radial_velocity_ref = "Spencer2017ApJ...836..202S"
sigma_v = 7.4
sigma_v_em = 0.4
sigma_v_ep = 0.4
sigma_v_ref = "Spencer2017ApJ...836..202S"
position_angle = 38.0
position_angle_em = 8.0
position_angle_ep = 8.0
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = 0.07
ellipticity_em = 0.01
ellipticity_ep = 0.01
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -9.72
Mv_em = 0.04
Mv_ep = 0.04
mv = 12.12
mv_em = 0.04
mv_ep = 0.04
mv_ref = "Munoz2018ApJ...860...66M"
rh = 2.52
rh_em = 0.03
rh_ep = 0.03
rh_ref = "Munoz2018ApJ...860...66M"
metallicity = -1.68
metallicity_em = 0.03
metallicity_ep = 0.02
metallicity_ref = "Simon2019ARA&A..57..375S"
