ra = 180.038
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Homma2018PASJ...70S..18H"
dec = -0.681
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Homma2018PASJ...70S..18H"
distance = 91.20108393559097
distance_em = 8.02470682532389
distance_ep = 8.798916064409028
distance_modulus = 19.8
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "Homma2024PASJ...76..733H"
pmra = nan
pmra_em = nan
pmra_ep = nan
pmra_ref = nan
pmdec = nan
pmdec_em = nan
pmdec_ep = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = 62.0
position_angle_em = 13.0
position_angle_ep = 8.0
postiion_angle_ref = "Homma2018PASJ...70S..18H"
ellipticity = 0.59
ellipticity_em = 0.14
ellipticity_ep = 0.12
ellipticity_ref = "Homma2018PASJ...70S..18H"
Mv = -0.9000000000000021
Mv_em = 0.65
Mv_ep = 0.72
mv = 18.9
mv_em = 0.65
mv_ep = 0.72
mv_ref = "Homma2024PASJ...76..733H"
rh = 1.76
rh_em = 0.4
rh_ep = 0.49
rh_ref = "Homma2018PASJ...70S..18H"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
