#!/bin/bash
#
#SBATCH	 -J	 isolation
#SBATCH --ntasks=16				#Number of cores
#SBATCH -A durham
#SBATCH -p cosma
#SBATCH -t 12:00:00
#SBATCH --mem-per-cpu=4G		#Memory per core
#SBATCH -o %J.out		#Standard output file

set -x 
rm -r out/* 
export OMP_NUM_THREADS=$SLURM_NTASKS
mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt > log.out

scontrol show job=$SLURM_JOB_ID
