ra = 15.0183
ra_err = 0.0012
ra_ref = "munoz+2018"
dec = -33.7186
dec_err = 0.0007
dec_ref = "munoz+2018"

distance = 83.2 
distance_err = 2
distance_modulus = 19.60
distance_modulus_err = 0.05
distance_ref = "tran+22"

pmra = 0.099 
pmra_err = 0.017
pmra_ref = "MV2020a"
pmdec = -0.160 
pmdec_err = 0.017 
pmdec_ref = "MV2020a"
pmra_note = "0.002 uncertainty but adds gaia systematics"

radial_velocity = 111.2
radial_velocity_err = 0.3
radial_velocity_ref = "arroyo-polonio+2024"

sigma_v = 9.7
sigma_v_err = 0.2
sigma_v_ref = "arroyo-polonio+2024"

ellipticity = 0.36
ellipticity_err = 0.01
ellipticity_ref = "munoz+2018"

position_angle = 92.0
position_angle_err = 1
position_angle_ref = "munoz+2018"

metallicity = -1.68
metallicity_err = 0.02
metallicity_ref = "MV2020a"

r_h = 12.33
r_h_err = 0.05
r_h_ref = "MV2020"

R_h = 9.79
R_h_err = 0.04
R_h_ref = "MV2020"
R_h_note = "also measured in munoz+2018"

R_h_inner = 9.46
R_h_inner_em = 0.26
R_h_inner_ep = 0.26


Mv = -10.82
Mv_err = 0.14
Mv_ref = "munoz+2018"

M_L_s = 1.4 
M_L_s_err = 0.3
theta_pm_gsr = -39.64 # atand(pmra_gsr, pmdec_gsr)
