ra = 15.0183
ra_err = 0.0012
dec = -33.7186
dec_err = 0.00072
distance = 83.2 
distance_err = 2
pmra = 0.099 
pmra_err = 0.002
pmdec = -0.160 
pmdec_err = 0.002
radial_velocity = 111.4 # this work
radial_velocity_err = 0.2

# this work
sigma_v = 9.61
sigma_v_err = 0.16

ellipticity = 0.36
ellipticity_err = 0.01
PA = 92
PA_err = 1

theta_pm_gsr = -39.64 # atand(pmra_gsr, pmdec_gsr)

Mv = -10.82
Mv_err = 0.14
M_L_s = 1.4 
M_L_s_err = 0.3
