ra = 15.0183
ra_err = 0.0012
ra_ref = "munoz+2018"
dec = -33.7186
dec_err = 0.00072
dec_ref = "munoz+2018"
distance = 83.2 
distance_err = 2
distance_ref = "tran+22"
pmra = 0.099 
pmra_err = 0.017 #0.002 + gaia sys
pmra_ref = "MV2020a"
pmdec = -0.160 
pmdec_err = 0.017 #0.002 + gaia sys
pmdec_ref = "MV2020a"
radial_velocity = 111.2 # this work
radial_velocity_err = 0.2
radial_velocity_ref = "this"

# this work
sigma_v = 9.69
sigma_v_err = 0.16
sigma_v_ref = "this"

ellipticity = 0.36
ellipticity_err = 0.01
ellipticity_ref = "munoz+2018"
position_angle = 92.0
position_angle_err = 1
position_angle_ref = "munoz+2018"


r_h = 12.33
r_h_err = 0.05
r_h_ref = "MV2020"

Mv = -10.82
Mv_err = 0.14
M_L_s = 1.4 
M_L_s_err = 0.3
theta_pm_gsr = -39.64 # atand(pmra_gsr, pmdec_gsr)
