ra = 101.18
ra_err = 0.0
ra_ref = "DrlicaWagner2016ApJ...833L...5D"
dec = -59.897
dec_err = 0.0
dec_ref = "DrlicaWagner2016ApJ...833L...5D"
distance = 45.708818961487516
distance_err = 3.050867081328171
distance_ref = "DrlicaWagner2016ApJ...833L...5D"
pmra = 1.15
pmra_err = 0.06
pmra_ref = "Battaglia2022A&A...657A..54B"
pmdec = 1.14
pmdec_err = 0.06
pmdec_ref = "Battaglia2022A&A...657A..54B"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 14.0
PA_err = 66.0
PA_ref = "DrlicaWagner2016ApJ...833L...5D"
ellipticity = 0.13
ellipticity_err = 0.22
ellipticity_ref = "DrlicaWagner2016ApJ...833L...5D"
Mv = -3.200000000000001
Mv_err = 0.5
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
