ra = 80.8
ra_err = 0.4
dec = -69.8
dec_err = 0.2
distance = 49.59
distance_err = 0.54
pmra = 1.910
pmra_err = 0.020 #0.002 + gaia sys
pmdec = 0.229
pmdec_err = 0.047 #0.002 + gaia sys
radial_velocity = 262 # this work
radial_velocity_err = 3
