ra = 19.47
ra_err = 0.0
ra_ref = "DrlicaWagner2015ApJ...813..109D"
dec = -17.42
dec_err = 0.0
dec_ref = "DrlicaWagner2015ApJ...813..109D"
distance = 29.922646366081892
distance_err = 2.7361368511517057
distance_ref = "DrlicaWagner2015ApJ...813..109D"
pmra = 2.844
pmra_err = 0.061
pmra_ref = "Pace2022ApJ...940..136P"
pmdec = 0.474
pmdec_err = 0.064
pmdec_ref = "Pace2022ApJ...940..136P"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = nan
PA_err = nan
PA_ref = "DrlicaWagner2015ApJ...813..109D"
ellipticity = nan
ellipticity_err = nan
ellipticity_ref = "DrlicaWagner2015ApJ...813..109D"
Mv = 0.0
Mv_err = 0.68
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
