#!/bin/bash

#SBATCH	 -J	 isolation
#SBATCH --ntasks=2				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 2:00:00
#SBATCH -p cosma			        #Queue name e.g. cosma, cosma6, etc.
#SBATCH --mail-user=dboyea@uvic.ca
#SBATCH --mail-type=END				#Notifications for job done & fail
#SBATCH -o %J.out		#Standard output file

module load gnu_comp
module load openmpi
module load fftw
module load hdf5
module load gsl

rm -r out/* 
mpirun -np $SLURM_NTASKS $GADGET_DIR/Gadget param.txt > log.out
# /cosma/home/durham/dc-boye1/dwarfs/gadget/Gadget4 param.txt
