#!/bin/bash

#SBATCH	 -J	 sculptor_orbit1
#SBATCH --ntasks-per-node=80
#SBATCH -t 12:00:00
#SBATCH -o %J.out		#Standard output file
#SBATCH --nodes=1

set -x

source $HOME/slurm_header.sh
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt > log.out


scontrol show job=$SLURM_JOB_ID
