#!/bin/bash
#SBATCH	-J	NGC_5466_mcmc
#SBATCH --ntasks=2
#SBATCH -t 0:10:00
#SBATCH --mem-per-cpu=4gb
#SBATCH -p cosma
#SBATCH -A durham
#SBATCH -o slurm_%j.out


set -x

rm -r out/*
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMC param.txt > log.out
