#!/bin/bash

#SBATCH	 -J	            isolation
#SBATCH --ntasks        16				#Number of cores
#SBATCH --nodes        2
#SBATCH --mem-per-cpu   2gb
#SBATCH -t              2:00:00
#SBATCH -o              %J.out
#SBATCH -A              $SLURM_ACCOUNT


source $HOME/slurm_header.sh

rm -rf out/* 
rm data/* 

mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt > log.out
