[[orbits]]
name = "mean"
ra = 209.3
dec = 26.8
distance = 46.559
pmra = -1.160
pmdec = -0.88
radial_velocity = 197.5


[[orbits]]
name = "smallperi"
ra = 209.3
dec = 26.8
distance = 46.0
pmra = -1.08
pmdec = -0.83
radial_velocity = 197.8


[[orbits]]
name = "largeperi"
ra = 209.3
dec = 26.8
distance = 47.1
pmra = -1.25
pmdec = -0.93
radial_velocity = 196.9

