[[orbits]]
name = "mean"
ra = 209.47
dec = 26.68
distance = 46.56
pmra = -1.16
pmdec = -0.88
radial_velocity = 188


[[orbits]]
name = "smallperi"
ra = 209.47
dec = 26.68
distance = 39.1
pmra = -1.15
pmdec = -0.88
radial_velocity = 188.1


[[orbits]]
name = "largeperi"
ra = 209.47
dec = 26.68
distance = 55.5
pmra = -1.17
pmdec = -0.88
radial_velocity = 187.9

