#!/bin/bash

#SBATCH	 -J	 compile_gadget
#SBATCH --ntasks=1				#Number of cores
#SBATCH -A $SLURM_ACCOUNT				#Account name
#SBATCH -t 1:00:00
#SBATCH -o %J.out		#Standard output file

# module load gsl

set -x
rm Gadget GadgetMW GadgetMC

SCRIPT_DIR="/home/dboyea/project/dwarfs/gadget"

cd ~/Gadget4
make CONFIG=$SCRIPT_DIR/Config.sh BUILD_DIR=$SCRIPT_DIR/build EXEC=$SCRIPT_DIR/Gadget
make CONFIG=$SCRIPT_DIR/ConfigMW.sh BUILD_DIR=$SCRIPT_DIR/build_mw EXEC=$SCRIPT_DIR/GadgetMW
make CONFIG=$SCRIPT_DIR/ConfigMC.sh BUILD_DIR=$SCRIPT_DIR/build_mc EXEC=$SCRIPT_DIR/GadgetMC
