ra = 213.909
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cerny2023ApJ...953....1C"
dec = 32.914
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cerny2023ApJ...953....1C"
distance = 101.85913880541169
distance_em = 6.7986594397835916
distance_ep = 7.284894839463803
distance_modulus = 20.04
distance_modulus_em = 0.15
distance_modulus_ep = 0.15
distance_ref = "Cerny2023ApJ...953....1C"
pmra = -0.22
pmra_em = 0.05
pmra_ep = 0.05
pmra_ref = "Cerny2023ApJ...953....1C"
pmdec = -0.28
pmdec_em = 0.07
pmdec_ep = 0.07
pmdec_ref = "Cerny2023ApJ...953....1C"
radial_velocity = 5.1
radial_velocity_em = 13.4
radial_velocity_ep = 13.4
radial_velocity_ref = "Smith2023AJ....166...76S"
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = "Smith2023AJ....166...76S"
position_angle = 18.0
position_angle_em = 13.0
position_angle_ep = 15.0
postiion_angle_ref = "Cerny2023ApJ...953....1C"
ellipticity = 0.2
ellipticity_em = 0.1
ellipticity_ep = 0.1
ellipticity_ref = "Cerny2023ApJ...953....1C"
Mv = -3.1999999999999993
Mv_em = 0.3
Mv_ep = 0.3
mv = 16.84
mv_em = 0.3
mv_ep = 0.3
mv_ref = "Cerny2023ApJ...953....1C"
r_h = 0.92
r_h_em = 0.26
r_h_ep = 0.19
r_h_ref = "J+24, Better measured in Cerny+2023"
metallicity = -2.85
metallicity_em = 0.1
metallicity_ep = 0.1
metallicity_ref = "Smith2023AJ....166...76S"
pmra_gsr = 0.12132892711576572
pmdec_gsr = 0.0640406693907866
radial_velocity_gsr = 81.162813018975
theta_pm_gsr = -39.64
