# MutluPakdil2018
ra = 359.1075
ra_err = 0.0
dec = -59.58332
dec_err = 0.0

distance = 22.9
distance_err = 1.1
pmra = -0.08
pmra_err = 0.01
pmdec = -1.62
pmdec_err = 0.02

# simon 2017
radial_velocity = -102.3
radial_velocity_err = 0.4

sigma_v = nan
sigma_v_err = nan 

ellipticity = 0.2
ellipticity_err = 0.1
PA = 25.0
PA_err = 38.0

# theta_pm_gsr =

Mv = -1.3
Mv_err = 0.2
M_L_s = 1.4 
M_L_s_err = 0.3
