ra = 28.772
ra_em = 0.0
ra_ep = 0.0
ra_ref = "J+24"

dec = -68.253
dec_em = 0.0
dec_ep = 0.0
dec_ref = "J+24"

distance = 71.1
distance_em = 3.3
distance_ep = 3.3
distance_modulus = 19.26
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "J+24"

ellipticity = 0.03
ellipticity_err = 0.13
ellipticity_ref = "J+24"
position_angle = 74
position_angle_err = 80
position_angle_ref = "J+24"


r_h = 1.02
r_h_err = 0.18
r_h_ref = "J24"

