#!/bin/bash

#SBATCH	 -J	 isolation
#SBATCH --ntasks=2				#Number of cores
#SBATCH -t 2:00:00
#SBATCH --mem-per-cpu=2gb


source /home/dboyea/slurm_header.sh

rm -r out/* 
mpirun -np $SLURM_NTASKS $GADGET_DIR/Gadget param.txt > log.out
# /cosma/home/durham/dc-boye1/dwarfs/gadget/Gadget4 param.txt
