ra = 209.8
ra_em = 0.1
ra_ep = 0.1
ra_ref = "this work"

ra_original = 209.3
dec_original = 26.8

dec = 26.7
dec_em = 0.1
dec_ep = 0.1
dec_ref = "this work"

distance = 46.55860935229591
distance_em = 3.9006574721366363
distance_ep = 4.257334903760167
distance_modulus = 18.34
distance_modulus_em = 0.19
distance_modulus_ep = 0.19
distance_ref = "Vivas+2020"


pmra = -1.16
pmra_em = 0.03
pmra_ep = 0.03
# including gaia systematic
pmra_ref = "battaglia+2022"

pmdec = -0.88
pmdec_em = 0.02
pmdec_ep = 0.02
pmdec_ref = "battaglia+2022"

radial_velocity = 190
radial_velocity_em = 1.8
radial_velocity_ep = 1.8
radial_velocity_ref = "Geha+2026"

sigma_v = 7.4
sigma_v_em = 2
sigma_v_ep = 2
sigma_v_ref = "Me"

position_angle = -81.0
position_angle_em = 8.0
position_angle_ep = 8.0
postiion_angle_ref = "moskowitz+walker2020"

ellipticity = 0.33
ellipticity_em = 0.09
ellipticity_ep = 0.09
ellipticity_ref = "moskowitz+walker2020"

Mv = -5.75
Mv_em = 0.6
Mv_ep = 0.6

mv = 12.6
mv_em = 0.5
mv_ep = 0.5
mv_ref = "MV2020"

r_h = 27
r_h_em = 5
r_h_ep = 6
r_h_ref = "J+24"

R_h = 27


metallicity = -2.0999999046325684
metallicity_em = 0.20000000298023224
metallicity_ep = 0.20000000298023224
metallicity_ref = "MV2020"

