# moskowitz2020
ra = 209.3
ra_err = 0.0
dec = 26.8
dec_err = 0.0

distance = 46.6
distance_err = 0.4

# pace 22
pmra = -1.176
pmra_err = 0.019
pmdec = -0.89
pmdec_err = 0.017

radial_velocity = 197.5
radial_velocity_err = 3.6

# carlin 2009
sigma_v = 10.7
sigma_v_err = 3.5

# munoz
ellipticity =0.33
ellipticity_err = 0.09
PA = 279
PA_err = 9

# theta_pm_gsr =

# correnti2009
Mv = -5.74
Mv_err = 0.5
M_L_s = 1.4 
M_L_s_err = 0.3

r_h = 33.03
r_h_err = 2.5
r_h_ref = "J24"
