ra = 209.3
ra_em = 0.0
ra_ep = 0.0
ra_ref = "grillmair2009"

dec = 26.8
dec_em = 0.0
dec_ep = 0.0
dec_ref = "grillmair2009"

distance = 46.55860935229591
distance_em = 0.42685189625800035
distance_ep = 0.43080150822559915
distance_modulus = 18.34
distance_modulus_em = 0.02
distance_modulus_ep = 0.02
distance_modulus_sys = 0.09
distance_ref = "Carlin2018ApJ...865....7C"
distance_notes = "suggest larger distance uncertainty of 2.0 kpc"

pmra = -1.160
pmra_em = 0.037
pmra_ep = 0.037
pmra_ref = "jensen+24"
pmdec = -0.88
pmdec_em = 0.035
pmdec_ep = 0.035
pmdec_ref = "jensen+24...940..136P"

radial_velocity = 197.5
radial_velocity_em = 3.8
radial_velocity_ep = 3.8
radial_velocity_ref = "carlin+2009"

sigma_v = 14.0
sigma_v_em = 3.2
sigma_v_ep = 3.2
sigma_v_ref = "carlin+2009"

position_angle = -81.0
position_angle_em = 8.0
position_angle_ep = 8.0
postiion_angle_ref = "moskowitz+walker2020"

ellipticity = 0.33
ellipticity_em = 0.09
ellipticity_ep = 0.09
ellipticity_ref = "moskowitz+walker2020"

Mv = -5.75
Mv_em = 0.6
Mv_ep = 0.6

mv = 12.6
mv_em = 0.5
mv_ep = 0.5
mv_ref = "MV2020"

r_h = 33.03
r_h_em = 2.50
r_h_ep = 2.50
r_h_ref = "J+24"

metallicity = -2.0999999046325684
metallicity_em = 0.20000000298023224
metallicity_ep = 0.20000000298023224
metallicity_ref = "MV2020"

