ra = 209.47
ra_err = 0.11
ra_ref = "this work"

ra_original = 209.3
dec_original = 26.8

dec = 26.68
dec_err = 0.06
dec_ref = "this work"

distance = 46.55860935229591
distance_em = 3.9006574721366363
distance_ep = 4.257334903760167
distance_modulus = 18.34
distance_modulus_em = 0.19
distance_modulus_ep = 0.19
distance_ref = "Vivas+2020"


# including gaia systematic
pmra = -1.16
pmra_em = 0.03
pmra_ep = 0.03
pmra_ref = "battaglia+2022"

pmdec = -0.88
pmdec_em = 0.02
pmdec_ep = 0.02
pmdec_ref = "battaglia+2022"

radial_velocity = 187
radial_velocity_em = 2
radial_velocity_ep = 2
radial_velocity_ref = "this work"

sigma_v = 7.7
sigma_v_em = 1.5
sigma_v_ep = 2
sigma_v_ref = "this work"

position_angle = 89
position_angle_em = 10
position_angle_ep = 10
postiion_angle_ref = "this work"

ellipticity = 0.42
ellipticity_em = 0.14
ellipticity_ep = 0.11
ellipticity_ref = "this work"

Mv = -5.1
Mv_em = 0.2
Mv_ep = 0.2
Mv_ref = "this work"

mv = 13.3
mv_em = 0.2
mv_ep = 0.2
mv_ref = "this work"

M_star = 14e3
M_star_err = 3e3

r_h = nan
r_h_em = nan
r_h_ep = nan
r_h_ref = "this work"

R_h = 44
R_h_em = 6
R_h_ep = 7


metallicity = -2.6
metallicity_em = 0.2
metallicity_ep = 0.2
metallicity_ref = "this work"

