ra = 209.48
ra_em = 0.10
ra_ep = 0.10
ra_ref = "this work"

ra_original = 209.3
dec_original = 26.8

dec = 26.67
dec_em = 0.05
dec_ep = 0.05
dec_ref = "this work"

distance = 46.55860935229591
distance_em = 3.9006574721366363
distance_ep = 4.257334903760167
distance_modulus = 18.34
distance_modulus_em = 0.19
distance_modulus_ep = 0.19
distance_ref = "Vivas+2020"


pmra = -1.16
pmra_em = 0.03
pmra_ep = 0.03
# including gaia systematic
pmra_ref = "battaglia+2022"

pmdec = -0.88
pmdec_em = 0.02
pmdec_ep = 0.02
pmdec_ref = "battaglia+2022"

radial_velocity = 187
radial_velocity_em = 2
radial_velocity_ep = 2
radial_velocity_ref = "this work"

sigma_v = 7.5
sigma_v_em = 1.5
sigma_v_ep = 2
sigma_v_ref = "this work"

position_angle = 93
position_angle_em = 10
position_angle_ep = 9
postiion_angle_ref = "this work"

ellipticity = 0.43
ellipticity_em = 0.12
ellipticity_ep = 0.12
ellipticity_ref = "this work"

Mv = -5.5
Mv_em = 0.3
Mv_ep = 0.3

mv = 12.6
mv_em = 0.5
mv_ep = 0.5
mv_ref = "this work"

r_h = nan
r_h_em = nan
r_h_ep = nan
r_h_ref = "this work"

R_h = 34
R_h_em = 4
R_h_ep = 5


metallicity = -2.6
metallicity_em = 0.2
metallicity_ep = 0.2
metallicity_ref = "this work"

