#!/bin/bash
#
#SBATCH	 -J	 isolation
#SBATCH -t 24:00:00
#SBATCH -o %J.out		#Standard output file
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=80

set -x 
source $HOME/slurm_header.sh
mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt 1 >> log.out

scontrol show job=$SLURM_JOB_ID
