#!/bin/bash
#
#SBATCH	 -J	 isolation
#SBATCH -t 5:00:00
#SBATCH -o %J.out		#Standard output file
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=80

set -x 
rm -r out/* 

source $HOME/slurm_header.sh
mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt > log.out

scontrol show job=$SLURM_JOB_ID
