#!/bin/bash
#
#SBATCH	 -J	 isolation
#SBATCH --ntasks=2				#Number of cores
#SBATCH -t 1:00:00
#SBATCH --mem-per-cpu=4G		#Memory per core
#SBATCH -o %J.out		#Standard output file
#SBATCH -p cosma
#SBATCH -A durham

source ~/slurm_header.sh
set -x 
rm -r out/* 
export OMP_NUM_THREADS=$SLURM_NTASKS
mpirun -np $SLURM_NTASKS $GADGET_DIR/Gadget param.txt > log.out

scontrol show job=$SLURM_JOB_ID
