#!/bin/bash

#SBATCH	 -J	 nfw_test
#SBATCH --ntasks=2			
#SBATCH -A durham				
#SBATCH -t 0:10:00
#SBATCH -p cosma			        
#SBATCH -o %J.out		

# these are defined in bash_profile

source ~/slurm_init.sh
rm -r out/*
mpirun -np "$SLURM_NTASKS" "$GADGET_PATH"/GadgetMW param.txt > log.out
