#!/bin/bash
#SBATCH	 -J	ngc2566
#SBATCH --ntasks=16
#SBATCH -t 8:00:00
#SBATCH -o %J.out		
#SBATCH --mem-per-cpu=4gb
#SBATCH --nodes=2

# #SBATCH -p cosma			        
# #SBATCH -A durham


rm -r out/* 
# mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt > log.out
srun $GADGET_PATH/GadgetMW param.txt > log.out
