#!/bin/bash

#SBATCH	 -J	 mc_sculptor     #Job name
#SBATCH --ntasks=2				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 2:00:00
#SBATCH -p cosma			    #Queue name e.g. cosma, cosma6, etc.
#SBATCH --mail-user=dboyea@uvic.ca
#SBATCH --mail-type=END				#Notifications for job done & fail
#SBATCH -o %J.out		#Standard output file

set -x

echo cleaning out
rm -r out/*
rm peris_apos.csv
rm log.out

echo running gadget
mpirun -np $SLURM_NTASKS $GADGET_DIR/GadgetHQ param.txt > log.out

# echo calculating peris
# julia  calc_peris.jl

echo finished

scontrol show job $SLURM_JOB_ID
