ra = 174.707
ra_em = nan
ra_ep = nan
ra_ref = "simonsmith+2024"

dec = 31.078
dec_em = nan
dec_ep = nan
dec_ref = "simonsmith+2024"

distance_modulus = 15.0
distance_modulus_em = 0.2
distance_modulus_ep = 0.2
distance_ref = "simonsmith+2024"

radial_velocity = 88.6
radial_velocity_em = 1.3
radial_velocity_ep = 1.3
radial_velocity_ref = "simonsmith+2024"

pmra = -0.75
pmra_em = 0.09
pmra_ep = 0.09
pmra_esys = 0.033
pmra_ref = "simonsmith+2024"
pmdec =  1.15
pmdec_em = 0.14
pmdec_ep = 0.14
pmdec_esys = 0.033
pmdec_ref = "simonsmith+2024"


ellipticity = 0.5
ellipticity_em = 0.3
ellipticity_ep = 0.2
ellipticity_ref = "simonsmith+2024"
position_angle = 169
position_angle_em = 12
position_angle_ep = 8
position_angle_ref = "simonsmith+2024"


r_h = 3
r_h_err = 1
r_h_ref = "simonsmith+2024"

Mv = 2.2
Mv_em = 0.3
Mv_ep = 0.4
mv_ref = "simonsmith+2024"

sigma_v = 3.7
sigma_v_em = 1.0
sigma_v_ep = 1.4
sigma_v_esys = 2.0
sigma_v_ref = "simonsmith+2024"

