#!/bin/bash

#SBATCH	 -J             isolation
# #SBATCH --ntasks        2
# #SBATCH --mem-per-cpu   4gb
#SBATCH -t              2:00:00
#SBATCH -o              %J.out
# #SBATCH -A              durham
# #SBATCH -p              cosma


# source $HOME/slurm_header.sh

rm out/* 
rm data/* 

mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt > log.out
