#!/bin/bash

#SBATCH	 -J	 isolation
#SBATCH --ntasks=2				#Number of cores
#SBATCH --mem-per-cpu=4gb
#SBATCH -A $SLURM_ACCOUNT				#Account name
#SBATCH -t 2:00:00
#SBATCH -o %J.out		#Standard output file

rm -r out/* 
export OMP_NUM_THREADS=$SLURM_NTASKS
mpirun -np $SLURM_NTASKS $GADGET_DIR/Gadget param.txt > log.out
# /cosma/home/durham/dc-boye1/dwarfs/gadget/Gadget4 param.txt
