#!/bin/bash

#SBATCH	 -J	 hernquist
#SBATCH --ntasks=2				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 2:00:00
#SBATCH -p cosma			        #Queue name e.g. cosma, cosma6, etc.
#SBATCH --mail-user=dboyea@uvic.ca
#SBATCH --mail-type=END				#Notifications for job done & fail
#SBATCH -o %J.out		#Standard output file

# these are defined in bash_profile
rm -r out/*
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMW param.txt > log.out
