#!/bin/bash

#SBATCH	 -J	            isolation
#SBATCH --ntasks        16				#Number of cores
#SBATCH --mem-per-cpu   5gb
#SBATCH -t              1:00:00
#SBATCH -o              %J.out
#SBATCH -A              durham
#SBATCH -p              cosma


source $HOME/slurm_header.sh

rm -rf out/* 
rm -rf data/* 

mpirun -np $SLURM_NTASKS $GADGET_PATH/Gadget param.txt > log.out
