#!/bin/bash

#SBATCH	 -J	sculptor_mc
#SBATCH --ntasks=2
#SBATCH -t 0:10:00
#SBATCH --mem-per-cpu=4gb

source ~/slurm_header.sh

rm -r out/*
mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMC param.txt > out/log.out
