ra = 227.2420
ra_err = 0.0045
dec = 67.2221
dec_err = 0.0016
distance = 70.1
distance_err = 2.9
pmra = -0.124
pmra_err = 0.017 #0.002 + gaia sys
pmdec = 0.078
pmdec_err = 0.017 #0.002 + gaia sys
# TODO revise...
radial_velocity = 246.9
radial_velocity_err = 0.4

# TODO: revise...
sigma_v = 8.0
sigma_v_err = 0.3

ellipticity = 0.55
ellipticity_err = 0.01
PA = 50
PA_err = 1

# theta_pm_gsr = -39.64 # atand(pmra_gsr, pmdec_gsr)

Mv = -9.03
Mv_err = 0.03
M_L_s = 1.4 
M_L_s_err = 0.3
