#!/bin/bash

#SBATCH	 -J	 crater_ii_mc
#SBATCH --ntasks=2				#Number of cores
#SBATCH -A durham
#SBATCH -p cosma
#SBATCH -t 0:10:00
#SBATCH -o %J.out		#Standard output file

# these are defined in bash_profile

set -x
export OMP_NUM_THREADS=$SLURM_NTASKS

rm -r out/*

mpirun -np $SLURM_NTASKS $GADGET_PATH/GadgetMC param.txt > out/log.out
