#!/bin/bash

#SBATCH	 -J	 isolation
#SBATCH --ntasks=2				#Number of cores
#SBATCH -A durham				#Account name
#SBATCH -t 2:00:00
#SBATCH -p cosma			        #Queue name e.g. cosma, cosma6, etc.
#SBATCH --mail-user=dboyea@uvic.ca
#SBATCH --mail-type=END				#Notifications for job done & fail
#SBATCH -o %J.out		#Standard output file
#SBATCH -e %J.err		#Error file

module load intel_comp/2019
module load intel_mpi/2019
module load fftw/2.1.5 
module load gsl/2.4
# module load gnu_comp/7.3.0 
module load hdf5

mpirun -np $SLURM_NTASKS /cosma/home/durham/dc-boru1/Gadget2_Noah/Gadget2-ABLL params_isolation.txt
