
# orbits
scl_orbits = ["sculptor", "EP2020"]
scl_lmc_orbits = ["sculptor", "vasiliev24_L3M11"]
umi_orbits = ["ursa_minor", "EP2020"]
umi_lmc_orbits = ["ursa_minor", "vasiliev24_L3M11"]

# results models
scl_smallperi = ["sculptor", "1e7_new_v31_r3.2/orbit_smallperi", "exp2d_rs0.10"]
scl_smallperi_plummer = ["sculptor", "1e7_new_v31_r3.2/orbit_smallperi", "plummer_rs0.20"]

scl_lmc = ["sculptor", "1e7_new_v25_r2.5/smallperilmc", "exp2d_rs0.10"]
scl_lmc_plummer = ["sculptor", "1e7_new_v25_r2.5/smallperilmc", "plummer_rs0.20"]

umi_smallperi = ["ursa_minor", "1e7_new_v38_r4.0/orbit_smallperi.5", "exp2d_rs0.10"]
umi_smallperi_plummer = ["ursa_minor", "1e7_new_v38_r4.0/orbit_smallperi.5", "plummer_rs0.20"]

