[[orbits]]
name = "mean"
ra = 15.0183
dec = -33.7186
distance = 83.2
pmra = 0.099
pmdec = -0.160
radial_velocity = 111.2

[[orbits]]
name = "smallperilmc"
ra               =  15.0183
dec              = -33.7186
distance         =  84.6
pmra             =   0.099
pmdec            =  -0.124
radial_velocity  = 111.2

[[orbits]]
name = "smallperi"
ra               =   15.0183
dec              =  -33.7186
distance         =   83.9
pmra             =    0.112
pmdec            =   -0.155
radial_velocity  =  111.2
