PSAT_min = 0.2
filename = "../processed/j24_sculptor_all.fits"
PA = 94
# dist = 83.2
# dist_err = 2
ra = 15.03917
pmdec = -0.16
ellipticity = 0.37
pmra = 0.099
dec = -33.70917



[profile_kwargs]
normalization = "none"

