ra = 13.158
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Munoz2018ApJ...860...66M"
dec = -72.8003
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Munoz2018ApJ...860...66M"
distance = 62.8058358813318
distance_em = 2.826728255780921
distance_ep = 2.959947854210185
distance_modulus = 18.99
distance_modulus_em = 0.1
distance_modulus_ep = 0.1
distance_ref = "Cioni2000A&A...359..601C"
pmra = 0.83
pmra_em = 0.02
pmra_ep = 0.02
pmra_ref = "Zivick2018ApJ...864...55Z"
pmdec = -1.21
pmdec_em = 0.01
pmdec_ep = 0.01
pmdec_ref = "Zivick2018ApJ...864...55Z"
radial_velocity = 145.6
radial_velocity_em = 0.6
radial_velocity_ep = 0.6
radial_velocity_ref = "Harris2006AJ....131.2514H"
sigma_v = 27.6
sigma_v_em = 0.5
sigma_v_ep = 0.5
sigma_v_ref = "Harris2006AJ....131.2514H"
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "Munoz2018ApJ...860...66M"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Munoz2018ApJ...860...66M"
Mv = -16.79
Mv_em = 0.2
Mv_ep = 0.2
mv = 2.2
mv_em = 0.2
mv_ep = 0.2
mv_ref = "deVaucouleurs1991rc3..book.....D"
r_h = 59.4
r_h_em = 4.1
r_h_ep = 4.1
r_h_ref = "Munoz2018ApJ...860...66M"
R_h = nan
R_h_em = nan
R_h_ep = nan
R_h_ref = "Munoz2018ApJ...860...66M"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
pmra_gsr = 0.34377395822746054
pmdec_gsr = -0.763823683117663
radial_velocity_gsr = -2.532977786705896
theta_pm_gsr = -39.64
