ra = 225.059
ra_em = 0.0
ra_ep = 0.0
ra_ref = "Cerny2023ApJ...953....1C"
dec = 5.909
dec_em = 0.0
dec_ep = 0.0
dec_ref = "Cerny2023ApJ...953....1C"
distance = 72.44359600749905
distance_em = 6.979978600771446
distance_ep = 7.724210331268836
distance_modulus = 19.3
distance_modulus_em = 0.22
distance_modulus_ep = 0.22
distance_ref = "Cerny2023ApJ...953....1C"
pmra = nan
pmra_em = nan
pmra_ep = nan
pmra_ref = nan
pmdec = nan
pmdec_em = nan
pmdec_ep = nan
pmdec_ref = nan
radial_velocity = nan
radial_velocity_em = nan
radial_velocity_ep = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_em = nan
sigma_v_ep = nan
sigma_v_ref = nan
position_angle = nan
position_angle_em = nan
position_angle_ep = nan
postiion_angle_ref = "Cerny2023ApJ...953....1C"
ellipticity = nan
ellipticity_em = nan
ellipticity_ep = nan
ellipticity_ref = "Cerny2023ApJ...953....1C"
Mv = -1.6000000000000014
Mv_em = 0.6
Mv_ep = 0.4
mv = 17.7
mv_em = 0.6
mv_ep = 0.4
mv_ref = "Cerny2023ApJ...953....1C"
rh = 0.74
rh_em = 0.11
rh_ep = 0.13
rh_ref = "Cerny2023ApJ...953....1C"
metallicity = nan
metallicity_em = nan
metallicity_ep = nan
metallicity_ref = nan
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64
