ra = 233.689
ra_err = 0.0
ra_ref = "Homma2019PASJ...71...94H"
dec = 43.726
dec_err = 0.0
dec_ref = "Homma2019PASJ...71...94H"
distance = 208.9296130854041
distance_err = 20.15715219137337
distance_ref = "Homma2019PASJ...71...94H"
pmra = -0.15
pmra_err = 0.1
pmra_ref = "MV2020b"
pmdec = -0.1
pmdec_err = 0.1
pmdec_ref = "MV2020b"
radial_velocity = nan
radial_velocity_err = nan
radial_velocity_ref = nan
sigma_v = nan
sigma_v_err = nan
sigma_v_ref = nan
PA = 3.0
PA_err = 4.0
PA_ref = "Homma2019PASJ...71...94H"
ellipticity = 0.64
ellipticity_err = 0.05
ellipticity_ref = "Homma2019PASJ...71...94H"
Mv = -5.34
Mv_err = 0.29
pmra_gsr = nan
pmdec_gsr = nan
radial_velocity_gsr = nan
theta_pm_gsr = -39.64

r_h = 7.6
r_h_arcmin = 0.8
r_h_ref = "MV2020"
